### ISSUE TITLE
Can't run selected query. Only Run All from Playground option available

### ISSUE THREAD

**Issue by prashantsharma** [mongodb-js/vscode#100]
First of all thanks for providing an official extension. 

I don't see an option to execute the selected query. I was using Azure Cosmos DB extension from some time and that provides an option to execute a selected query.

Is it possible to get a similar feature with an extension?

**Comment by Anemy** [comment]
Hi Prashant,

This is something we have planned :) 

If you have any other ideas or suggestions, we've got a feedback forum that's probably best suited for it: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code

Thanks for the trying out the extension - we'll be adding more features in the coming weeks & months.
