### ISSUE TITLE
Mongo Shell launch error

### ISSUE THREAD

**Issue by rafee** [mongodb-js/vscode#101]
I get the following error when I try to connect to launch the shell.

`FailedToParse: Database name cannot have reserved characters for mongodb:// URL: mongodb+srv://admin:`

Environment Details:
VSCode: 1.45.1
OS: WSL Ubuntu 20.04
Mongo Shell: 3.6.8

**Comment by alenakhineika** [comment]
Try to change your default Shell in VSCode. Run the `Terminal: Select Default Shell` from the command palette and select Windows PowerShell. Note that you should reopen the terminal to apply the configuration.

We have a ticket for opening mongodb shell gracefully on all environments, we will check if we can preselect PowerShell automatically for Windows/WSL environments.

**Comment by rafee** [comment]
Does that mean mongo shell doesn't work with WSL?

**Comment by Anemy** [comment]
@rafee version `0.0.4` is live with a fix for mongo shell in various environments. We'll close this issue, but please feel free to reopen if you find the issue is still happening.

Thanks!
