### ISSUE TITLE
SSH Tunneling via Identity File fails on Windows

### ISSUE THREAD

**Issue by luastoned** [mongodb-js/vscode#103]
Hi,

I'm trying to access a mongo instance on a secure server with username/private key auth.
The path to the selected key file looks weird (as in being prefixed with `/C:/Users/.../pk`)

On connecting it shows `Failed to connect: Error creating SSH Tunnel: All configured authentication methods failed`

The same method works for Robo3T, so I would expect it to work here too.

**Comment by Anemy** [comment]
@luastoned Hey Lua, we've just pushed the new version now which should fix this issue (0.0.3). Feel free to reopen if the issue hasn't gone away. Thanks for bringing up!
