### ISSUE TITLE
Cannot Connect to Atlas Cluster - querySrv ETIMEOUT 

### ISSUE THREAD

**Issue by hc-danieltiziani** [mongodb-js/vscode#104]
I've tried to connect to my clusters over atlas, but it always get an error: 

```Unable to create connection: Error: querySrv ETIMEOUT _mongodb._tcp.<REDACTED>.mongodb.net```

I've tried to switch databases, but with no success.

**Comment by alenakhineika** [comment]
Are you able to connect to the same cluster via Compass or shell?
