### ISSUE TITLE
Not loading PEM file on Windows 10

### ISSUE THREAD

**Issue by srayatcsg** [mongodb-js/vscode#105]
Failing to connect with error "Failed to connect: ENOENT: no such file or directory, open 'C:\C:\xx.pem'. Note the double drive letter. Tried using both admin and non-admin accounts.

Same connection works through MongoDB Compass.

**Comment by Anemy** [comment]
Thanks for reporting, this is definitely a bug. We've got another report so I'm closing this as a duplicate, lets use: https://github.com/mongodb-js/vscode/issues/105 in future.

**Comment by Anemy** [comment]
@srayatcsg Hi Stephen, we've just pushed the new version now which should fix this issue. Feel free to reopen if the issue hasn't gone away. Thanks again for bringing it up.
