### ISSUE TITLE
ObjectId syntax

### ISSUE THREAD

**Issue by michae1** [mongodb-js/vscode#108]
I have found the unfamiliar syntax of objectId. Is it designed that way or a kind of a bug?

Usual syntax in other clients:
```db.collection.find({users: {$eq: ObjectId(ID)}})```

Which throws ```Cannot call a class as a function```

Working syntax in Mongo VSCode:
```db.collection.find({users: {$eq: new ObjectId(ID)}})```

**Comment by mmarcon** [comment]
@Anemy @alenakhineika let's pull the latest shell runtime so we get support for BSON object constructors without `new`.

**Comment by Anemy** [comment]
@michae1 We've just pushed up the new version now which should fix this issue (0.0.3). Feel free to reopen if the issue hasn't gone away. Thanks for letting us know.
