### ISSUE TITLE
Explain does not bring back all data

### ISSUE THREAD

**Issue by rwilliams-home** [mongodb-js/vscode#111]
explain("executionStats") only brings back plan data, but not the executionStats when running in the playground. One of the main reasons for running is to determine indexing requirements and I need the stats from execution.

**Comment by alenakhineika** [comment]
It looks like you are trying to use `explain("executionStats")` with aggregation. Currently, `executionStats` is supported only by the `find()` operation, and not supported by `aggregate()`.
