### ISSUE TITLE
Playground imports or requires

### ISSUE THREAD

**Issue by rwilliams-home** [mongodb-js/vscode#112]
I often use moment to format the results or the parameters of my queries. the playground does not support either a require or imports to use other JS libs.

**Comment by alenakhineika** [comment]
We checked this and yes this is a bug with our runtime. I'll message here once it fixed. Thanks for bringing it up!

**Comment by alenakhineika** [comment]
The version 0.0.3 is released that adds require support in playgrounds. Thanks again for letting us know about the issue!
