### ISSUE TITLE
Some schemas do not display type information

### ISSUE THREAD

**Issue by rwilliams-home** [mongodb-js/vscode#113]
Not sure of the criteria for determining types. but I have one larger collection that just shows question marks for the data type when looking in the schema. Other collections mostly good with a few data types missing.

**Comment by alenakhineika** [comment]
The type of field is unknown when different documents in the collection have different types of values stored in this field. For example, time can be stored as a string or number, and in this case, we show a question mark icon.

When creating a collection there is a possibility to specify JSON schema rules: https://docs.mongodb.com/manual/core/schema-validation/

The schema validation will ensure that all document fields have a proper type.
