### ISSUE TITLE
Every Document is opened on new tab .

### ISSUE THREAD

**Issue by jaskeerat789** [mongodb-js/vscode#115]
Every time I want to check a doc, It opens it in a new tab Which makes it difficult to navigate across the workspace. I would recommend open docs in the same tab and maybe device some mechanism to open the docs in a new tab if the user wants to compare two or more of them.

**Comment by jaskeerat789** [comment]
Like we can have ctrl+left-click to open documents in a new tab.

**Comment by Anemy** [comment]
Hi Jaskeerat,

This could be a setting we can expose - Open documents in new a tab or the same tab if a document is already open.
Currently it's possible to view multiple documents in the same tab by right clicking the collection and selecting `View Documents`.

If you have any other ideas or suggestions, we've got a feedback forum that's probably best suited for it: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code

**Comment by mmarcon** [comment]
@jaskeerat789 I submitted the idea on your behalf in our forum: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/40504408-open-documents-in-the-same-tab. You can follow the progress there.

**Comment by jaskeerat789** [comment]
thanks, @mmarcon , I'll keep a track of it
