### ISSUE TITLE
FEATURE REQUEST Edit playground results, to save documents.

### ISSUE THREAD

**Issue by manudevcode** [mongodb-js/vscode#121]
In other extensions, you can edit the json that results in running the playground and thus update the documents in the database.

<img width="1053" alt="Captura de Pantalla 2020-05-26 a la(s) 11 53 22" src="https://user-images.githubusercontent.com/11260098/82928188-815be880-9f47-11ea-81f3-a860eba860ab.png">

**Comment by mmarcon** [comment]
We have this in our todo list and there is a [feature request](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/40436602-write-mode) in our feedback forum.

**Comment by Anemy** [comment]
@manudevcode We've just release `0.4.0` which has this feature :D - feel free to upgrade and let us know how it goes.
