### ISSUE TITLE
Code formatting in .mongodb

### ISSUE THREAD

**Issue by delcon** [mongodb-js/vscode#122]
Is there any way to configure / use a formatter / linter for .mongodb files?
This is my no1 feature that I miss in all mongodb GUI and would save me the countless times I try to run a query - just to get notified that something is not formatted right.

**Comment by mmarcon** [comment]
As a workaround, you could use the [Beautify extension](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify).

I know it's not the best solution but it gets the job done.

![2020-05-29_09-29-01 (1)](https://user-images.githubusercontent.com/761042/84888109-12316a00-b097-11ea-964e-dda17672becc.gif)

**Comment by mmarcon** [comment]
Can you create a feature request in our [feedback forum](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code)?

**Comment by charlesonunze** [comment]
You can also add this to your `settings.json` file.

```json
	"files.associations": {
		"*.mongodb": "javascript"
	}
```

**Comment by mmarcon** [comment]
> You can also add this to your `settings.json` file.
> 
> ```json
> 	"files.associations": {
> 		"*.mongodb": "javascript"
> 	}
> ```

@charlesonunze this actually breaks playgrounds as they will be identified as JS files and the extension won't add the playground-related features anymore.

**Comment by charlesonunze** [comment]
Shit, I actually did not think that was the issue when intellisense wasn't working. I guess it needs it's own formatted after all :(

**Comment by Flamefork** [comment]
Prettier could be integrated too, although not in a straight way:
1. adding to vscode config
```
  "prettier.documentSelectors": [
    "**/*.mongodb"
  ],

```
2. adding to `.prettierrc` or creating one
```
{
  "overrides": [
    {
      "files": "*.mongodb",
      "options": {
        "parser": "babel"
      }
    }
  ]
}
```

**Comment by charlesonunze** [comment]
This actually works! Thanks! @Flamefork

**Comment by alenakhineika** [comment]
I am closing this issue, but we have a formatting enhancement request on the MongoDB forum that you can track: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/42380848-formatting-support-for-mongodb-playground-files

And feel free to reach out if you have any further questions!

**Comment by mainakchhari** [comment]
this overrides section is not working when added to the global ~/.prettierrc
