### ISSUE TITLE
Keyboard Shortcut

### ISSUE THREAD

**Issue by delcon** [mongodb-js/vscode#123]
With Code-Runner I can run the active .js file with Alt-r.  
It would be great to be able to configure code-runner, or the extension for a Keyboard-Shortcut

**Comment by mmarcon** [comment]
Hi @delcon, in VS Code you can assign yourself keyboard shortcuts to your favorite commands.

In the example below, you can see how I assigned `Ctrl + Options + Cmd + R` to the Run All From Playground command.

![image](https://user-images.githubusercontent.com/761042/83007508-188e7200-a014-11ea-87c2-cea21a6e1178.png)

If you go to `Preferences > Keyboard Shortcuts` you can search for the command you want to assign a shortcut to and pick your shortcut for it. All the commands for all the extensions are available on that list.

![image](https://user-images.githubusercontent.com/761042/83007911-a8342080-a014-11ea-85db-f9273c1613b4.png)

I hope this helps.

**Comment by delcon** [comment]
You should add a condition to MongoDB: Run All From Playground
As it is right now this gets triggered in all files, not just mongodb files - and interferes with other commands

![image](https://user-images.githubusercontent.com/9477898/92442559-676dab00-f1b0-11ea-9a62-fb1a81365a35.png)
