### ISSUE TITLE
Feature Request - Please add Kerberos authentication

### ISSUE THREAD

**Issue by sunilunnithan** [mongodb-js/vscode#124]
Hi,

I do not see GSSAPI in the available list of authentications.  All our clusters are Kerberos enabled to support strong authentication.

Thanks

**Comment by mmarcon** [comment]
Tracked in our feedback forum: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/40536571-kerberos-authentication-for-vscode.

I will close this issue.
