### ISSUE TITLE
[Feature Request] Output to temp JSON editor view instead of VSCode Output view

### ISSUE THREAD

**Issue by Jule-** [mongodb-js/vscode#125]
When you are working with JSON results I think it is a better choice to use full VSCode handling of this kind of data in a standard editor tab view: syntax coloration, (un)folding, edition in order to copy/past for a further update, etc...
The output view is giving a poor experience IMHO.

Thanks again for this promising extension! 😉

**Comment by mmarcon** [comment]
This is now implemented and released in version 0.3.0.
Results of playgrounds go to an editor tab, while output printed with `console.log` and `print` is shown in Output.

**Comment by Jule-** [comment]
Many thanks this is perfect! 👌 🙂
