### ISSUE TITLE
Option to disable comments for aggregation stages

### ISSUE THREAD

**Issue by yojeek** [mongodb-js/vscode#129]
## Detailed Description

Option to disable comments for aggregation stages by default. I would assume that link to documentation website will make more sense, considering complexity of aggregation stage use cases. And even that should be optional.

## Context

I run a lot of quick aggregations to get data insights, comments are just wasting 50% of playground's screen space and not too helpful for me.

**Comment by mmarcon** [comment]
I transferred this suggestion to our feedback forum, which is where we keep track of the feedback for all MongoDB products: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/40686811-option-to-disable-comments-for-aggregation-stages.

We will keep this in mind although with snippets this is something that isn't possible to do so we'd have to implement our own logic to handle it.
