### ISSUE TITLE
Broken: Autocompletion and playground with Remote-WSL

### ISSUE THREAD

**Issue by andreialecu** [mongodb-js/vscode#133]
#### Current Behavior

Pressing `ctrl+space` as instructed after a dot makes the list get stuck on `Loading...`.

![image](https://user-images.githubusercontent.com/697707/84369670-df432e00-abdf-11ea-8198-253f46a2296e.png)

Additionally, trying to run the playground does nothing, the output window remains blank and it appears nothing is ran.

I noticed these errors appearing in the VSCode console:

![image](https://user-images.githubusercontent.com/697707/84369536-a4d99100-abdf-11ea-901c-16d700e98ccd.png)

Which seem to be coming from the extension.

It connected successfully to an Atlas database, and I can properly browse things in the `MongoDB` pane.

I'm using VSCode 1.45.1 and extension version 0.0.3.

**Comment by andreialecu** [comment]
In the initial report I was running the VSCode and the extension via `Remote-WSL` in `WSL: Ubuntu`.

Ref: https://code.visualstudio.com/docs/remote/wsl

It appears that when running outside of `Remote-WSL`, the extension works properly, even though the error is still logged.

**Comment by Anemy** [comment]
Hi Andrei, thanks for bringing this up - we have a fix for this going into our next release (0.0.4). I'm going to close this ticket if that's alright, we can use https://github.com/mongodb-js/vscode/issues/94
