### ISSUE TITLE
Cannot expand collections when used with non-admin user

### ISSUE THREAD

**Issue by andreialecu** [mongodb-js/vscode#134]
I have a non admin user which only has access to a specific database. The connection string includes the database, and MongoDB Compass works with that specific connection string: 

`mongodb+srv://....mongodb.net/DBWITHACCESS?authSource=admin&replicaSet=Cluster0-shard-0&readPreference=primary&ssl=true`

However, when trying to expand the tree in the `MongoDB` pane, it fails with this error:

`Unable to list databases: user is not allowed to do action [listDatabases] on [admin.]`

**Comment by andreialecu** [comment]
Also reported at #96

**Comment by mmarcon** [comment]
Closing as a duplicate.
