### ISSUE TITLE
Publish the extension to open-vsx.org as well.

### ISSUE THREAD

**Issue by sagar98ch** [mongodb-js/vscode#135]
please publish the extension to [open-vsx.org](https://open-vsx.org/) as well, Open VSX is an open-source registry for VS Code extensions maintained by [eclipse-foundation](https://projects.eclipse.org/projects/ecd.openvsx).

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Comment by vymarkov** [comment]
I'd like to see this extension on https://open-vsx.org due to I'm as active user of VSCodium and Gitpod as well.

**Comment by kittaakos** [comment]
It's already available: https://open-vsx.org/extension/mongodb/mongodb-vscode

**Comment by Anemy** [comment]
At the moment Open VSX is not something we're supporting yet. I think this might be a better topic for our feedback forum which allows for upvotes: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code
If we find enough support it's definitely something we'd be open to.

To be clear, we are **not** the publishers of the current extension on open-vsx.

Going to close this issue if that's alright - thanks for opening it!
