### ISSUE TITLE
Feature Request - "View Document" in context menu

### ISSUE THREAD

**Issue by jcgerhard** [mongodb-js/vscode#143]
## Feature Request

Having a "View Document" option in a documents' context menu

## Detailed Description

To get a more fluent way of working with a mongo instance, it would be nice to have this additional option in the mouse context menu of a document entry.

## Context

I have been working with the extension solely for a few weeks now. I really love it beacause there is no need to left VS Code to work on a database anymore. I would like to replace my mongodb client completely with this extension.
This feature would make it sometimes more intuitive to use while working the hole day with it.

## Possible Implementation

![mongo-vscode-document-view](https://user-images.githubusercontent.com/29855366/86919498-9d4ad080-c128-11ea-986c-29a95236837d.jpg)

**Comment by mmarcon** [comment]
@jcgerhard what's the reason for wanting View Document in the contextual menu vs just clicking on the document?

**Comment by jcgerhard** [comment]
To be honest: just for completness. But when I think twice...you are right...maybe it‘s redundant. 🤓

**Comment by Anemy** [comment]
This is released in the new `0.10.0` version. Thanks for opening the issue!
https://github.com/mongodb-js/vscode/releases

**Comment by jcgerhard** [comment]
That's great! I thought this project has died. I will test it. Keep up!
