### ISSUE TITLE
Feature Request - "Drop Document" option in context menu

### ISSUE THREAD

**Issue by jcgerhard** [mongodb-js/vscode#145]
## Feature Request

Having a "Drop Document" option in a documents' context menu

## Detailed Description

To get a more fluent way of working with a mongo instance, it would be nice to have this additional option in the mouse context menu of a document entry. I oftentimes need to drop/delete documents while working on a collection.
This feature would make it way more easy to do this.

## Context

I have been working with the extension solely for a few weeks now. I really love it beacause there is no need to left VS Code to work on a database anymore. I would like to replace my mongodb client completely with this extension.
This feature would make it way more comfortable to use while working the hole day with it.

## Possible Implementation

![mongo-vscode-document-drop](https://user-images.githubusercontent.com/29855366/86920826-94f39500-c12a-11ea-8ca6-9d358b8a3b32.jpg)

**Comment by alenakhineika** [comment]
Could you please create a feature request in our [feedback forum](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code)?

**Comment by SethFalco** [comment]
I'll implement this next week as a part of https://github.com/mongodb-js/vscode/pull/419 if that isn't merged already. If it gets merged by then, I'll do it separately since I worked in that area anyway. 👍🏾 

I'd probably call it "Delete Document…" instead of "Drop Document".

I'm not sure what the best UX is, but will likely add an "Are you sure?" prompt somehow where it shows the user the document and they have to click type `y` or click "Yes" in a prompt or something.

**Comment by santiagopuentep** [comment]
This feature looks critical to me. I have no idea of how to delete documents using the extension, without doing it with a playground. Am I missing something?

**Comment by Anemy** [comment]
@jcgerhard @santiagopuentep 
We've added document actions in the new `0.10.0` release. Thanks for opening the issue and the good writeup!
https://github.com/mongodb-js/vscode/releases

**Comment by jcgerhard** [comment]
That's great! I thought this project has died. I will test it. Keep up!

**Comment by santiagopuentep** [comment]
I tried it and it's not working. There's not even context menu when right clicking on a document.

**Comment by Anemy** [comment]
@santiagopuentep Are you sure you're using the most up to date version of the extension? `0.10.0`? The extension auto update in VSCode can take a bit to update. You might have to restart VSCode.
Here's what right clicking a document should look like:
<img width="353" alt="Screen Shot 2023-01-13 at 10 22 39 AM" src="https://user-images.githubusercontent.com/1791149/212356815-933b235c-7be4-4600-9495-220d363a43fa.png">

**Comment by santiagopuentep** [comment]
@Anemy Yes, I have `0.1.0`, and I had restarted VSCode, but now I restarted it again just in case and now it works. Thanks.
