### ISSUE TITLE
Question - Linting

### ISSUE THREAD

**Issue by MridulaKamath** [mongodb-js/vscode#155]
Are there any built-in options or other VSCode extensions available for verifying query syntax, best practices, etc. similar to ESLINT?

**Comment by Anemy** [comment]
Hi @MridulaKamath  are you looking for linting/syntax in playgrounds or in a particular language?

**Comment by MridulaKamath** [comment]
@Anemy In the playground. The extension is great! Really enjoying working with it. :)

**Comment by Anemy** [comment]
Thanks again for reporting, going to close this as a duplicate, we can use https://github.com/mongodb-js/vscode/issues/122 going forward for updates.

**Comment by mmarcon** [comment]
Captured in our feedback portal: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/41247265-linting-validation-support-for-query-language
