### ISSUE TITLE
Feature Request - Output to file

### ISSUE THREAD

**Issue by ssipos90** [mongodb-js/vscode#158]
## Feature Request
I'd like to output to a new editor as JS(ON) instead of the output panel.

```JSON
// first command
{"someProp": 3}

// second command
["bla", "blah"]

// third command
"some output"
```
## Context
Allows easy searching, navigation and manipulation of the output. Makes data more readable by using syntax highlighting.

## Possible Implementation
Perhaps an option in the settings of the plugin to set the preferred output or another command to run the playground and output to new editor or something in the middle - like when you select `Debug: Select and start debugging` and then it prompts you to choose which script - it could allow you to choose outputs or something similar.

A problem might be that the output might not be valid JS because you need to `let variable = ...` in front of any `[...]` or `{...}`.
Another way would be to output to JSON. It would be a bit invalid, having multiple root items. I've seen JSON being used like this, supporting multiple roots (eg: i3wm workspace JSON files) separated by an empty comment and some parsers support this.

Thanks

**Comment by Anemy** [comment]
Hi @ssipos90 - thanks for the suggestion! We're planning to improve how we output playground results soon. I'm going to close this ticket if it's alright, we've got another that's looking for a similar feature: https://github.com/mongodb-js/vscode/issues/125 . Thanks again - let us know if you think of any more ways we can improve the extension :)
