### ISSUE TITLE
Dropping database should remove it from tree view

### ISSUE THREAD

**Issue by Xeevis** [mongodb-js/vscode#165]
When database is dropped, it stays visible until full manual tree refresh is performed.

![asd](https://i.imgur.com/Nql4FiU.gif)

**Comment by Anemy** [comment]
Thanks for the good gif! I'll post when we've got an update out that fixes this.

**Comment by Xeevis** [comment]
Fixed with https://github.com/mongodb-js/vscode/pull/288
