### ISSUE TITLE
Bug Report: vscode "run all" command no longer shows up when searching for vscode commands

### ISSUE THREAD

**Issue by benatshippabo** [mongodb-js/vscode#196]
#### Current Behavior

Regression on vscode command to run all mongodb playgrounds. Before you could `cmd + shift + p` and then search to run all mongodb playgrounds, but now it's no longer present and we only have the play button.

#### Environment

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (2 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
mongodb.mongodb-vscode: v0.2.1
```

#### Possible Solution

Please add the vscode command back so it is searchable again. 🙏 

#### Additional Context/Screenshots

![image](https://user-images.githubusercontent.com/66273043/97645876-56e8ec80-1a0b-11eb-9295-614f5c2258dc.png)

**Comment by Anemy** [comment]
Thanks for the report - definitely a bug. We'll wrap a fix for this into the current work around improving playgrounds and get it out soon! I'll ping here when it's live.

**Comment by mmarcon** [comment]
The fix will be in the next release.
