### ISSUE TITLE
Feature Request - Option to switch focus to playground result

### ISSUE THREAD

**Issue by MatthewS2077** [mongodb-js/vscode#222]
## Feature Request

Option to switch focus to playground result.

## Detailed Description

Add option _Switch focus to Playground Result_ which defaults to true (the current behaviour). 

If false, then running a query will not switch focus to the Playground Result but leave focus in the Playground.

## Context

It's annoying to have focus switch to Playground Result.  I prefer focus to stay where it is.

**Comment by Anemy** [comment]
Hi @MatthewS2077 thanks for the good feature request. Created a jira ticket to track progress: https://jira.mongodb.org/browse/VSCODE-214

**Comment by MatthewS2077** [comment]
Any news on this?  The extension is great but switching focus to the results pane automatically is a bad UX,  IMHO 🤷‍♂️

For my setup, my results pane is to the right of my editor pane, so I can see both at once. If I'm testing aggregations I make a quick change, run, check result... but focus is switched to the output pane and I need to switch focus back to my editor pane to make another change... this is very annoying 🤬.   Otherwise this extension is 👍👍👍

**Comment by alenakhineika** [comment]
Hey, the team is going to triage the ticket and you can track progress here or in Jira: https://jira.mongodb.org/browse/VSCODE-214

**Comment by alenakhineika** [comment]
Hey, `0.6.0` is live with an update to preserve focus in playgrounds after running them! Closing this issue, feel free to reopen if you find any issues with it.
