### ISSUE TITLE
Bug Report: Not able to connect to the local MongoDB

### ISSUE THREAD

**Issue by yashrahurikar23** [mongodb-js/vscode#229]
#### Current Behavior

When I try to connect to the local MongoDB it just keeps connecting..  

#### Expected Behavior/Code

Ideally it should show me the collections in my local Mongo

#### Environment

- node.js / npm versions: [e.g. node v10.3.0 / npm 6.7.1]
- OS: [Ubuntu 20.04]

**Comment by Anemy** [comment]
Hi @yashrahurikar23 a few questions to help us debug this - how are you connecting? With connection string or connection form?
Is it a standalone instance or a replica set?
Can you connect to this local instance with shell?

**Comment by yashrahurikar23** [comment]
Hi @Anemy 
Thank you for replying
I am connecting via the form
It is a standalone instance
Yes I can connect to the instance with shell

I also wanted to ask if this might be because of some user permission issues with VS Code?, as I am trying all this on Linux

**Comment by addaleax** [comment]
I’m also Ubuntu 20.04, and I can connect to localhost. Which versions of vscode and the extension are you using? How did you install them?

**Comment by yashrahurikar23** [comment]
I am using VS code version 1.46.0
Mongo DB for VS code version 0.2.0

**Comment by yashrahurikar23** [comment]
With the new update for the extension, I am able to connect to the local Mongo
