### ISSUE TITLE
Failed to connect: unable to verify the first certificate

### ISSUE THREAD

**Issue by kirkfox** [mongodb-js/vscode#238]
I am receiving this error when using the same connection string that works in robo3t.  Is there a workaround or a way to see what is causing this error?

**Comment by Anemy** [comment]
@kirkfox Are you using certificates in your connection string? How is the connection configured? Are you connecting with a connection string or the connection form?
The `unable to verify the first certificate` is an error the driver is giving us.
Thanks for checking out the extension!

**Comment by kirkfox** [comment]
Thanks for the quick response.  I was finally able to get it to work via the Advanced Connection Settings by setting the SSL to Unvalidated.  I have yet to find the equivalent in the connection string for MongoDB 4.0
