### ISSUE TITLE
Feature Request: Delete documents (right click)

### ISSUE THREAD

**Issue by manudevcode** [mongodb-js/vscode#247]
## Feature Request
Delete documents with right click

## Detailed Description
Delete documents with right click like image below: 

![Captura de Pantalla 2021-01-28 a la(s) 0 15 13](https://user-images.githubusercontent.com/11260098/106098084-0b270b80-60fe-11eb-83fb-d2f51983af1c.png)

**Comment by Anemy** [comment]
Hi @manudevcode going to close this - we've got https://github.com/mongodb-js/vscode/issues/145 which I think is looking for the same functionality. Question around the functionality though, would you expect a confirmation dialogue after clicking delete?
Thanks for the good feature request and for trying out the extension!
