### ISSUE TITLE
Playground tries to use local network name when executing queries

### ISSUE THREAD

**Issue by andokai** [mongodb-js/vscode#249]
#### Current Behavior

I have a MongoDB instance running in the cloud. Most of the extension functionality works fine but the playground has broken with a recent release. When I try to execute a query I get an error "getaddrinfo ENOTFOUND <machinename>" where <machinename> is the name of the VM MongoDB is running on.

**Comment by Anemy** [comment]
Thanks for reporting, a couple questions to help us understand this issue.
Are you connected to this instance on connection explorer panel when you run the playground?
Did you add this connection with a connection string or through the form? How is it configured (standalone, replica set, authentication method, ssl/tls options, ssh tunnel)?
Which queries are you trying to run? (Or does it not matter which query).

**Comment by andokai** [comment]
> Thanks for reporting, a couple questions to help us understand this issue.
> Are you connected to this instance on connection explorer panel when you run the playground?

Yes, and that aspect works fine. I can browse the collections and view/edit the documents

> Did you add this connection with a connection string or through the form? How is it configured (standalone, replica set, authentication method, ssl/tls options, ssh tunnel)?

I tried with a connection string and with the form, it didn't make a difference. Authentication mode is just a username and password with no SSL. It's not a replica set either. The connection string with the sensitive bits removed

mongodb://user:password@external-name.westeurope.cloudapp.azure.com:27017/?authSource=admin&readPreference=primary&ssl=false

> Which queries are you trying to run? (Or does it not matter which query).

It doesn't matter

**Comment by Anemy** [comment]
Looks like this is related to a mongodb node driver change, the playground runs are using the newer mongodb node driver in the vscode extension 0.4.0 release. The main extension is on an older version of the driver. The main difference is that `directConnection` used to be defaulted to `true` when connecting to an individual node. Here's the change for reference: https://github.com/mongodb/node-mongodb-native/commit/f8fd310a11a91db82f1c0ddc57482b8edabc231b#diff-27b23bbca267efc75c0a7cdedd96de574c7747f5896f15f985d32b62b1106d85L696

We'll release a fix for this in the next few days/weeks, in the meantime does setting `directConnection=true` on the connection string fix the issue?

**Comment by andokai** [comment]
Yes, adding that to the connection string fixes the issue 👍

**Comment by Anemy** [comment]
@andokai We've just release `0.4.1` which has a fix for this :) Thanks again for bringing it up!

**Comment by andokai** [comment]
Good news, thanks for sorting so quickly!
