### ISSUE TITLE
Unable to connect to local mongodb on WSL2

### ISSUE THREAD

**Issue by PGlivicky** [mongodb-js/vscode#253]
When trying to connect to a local mongodb, I'm getting: `Unknown or unsupported transport “disabled” for address “disabled:”` I'm running VS Code in WSL2 (Ubuntu).
#### Current Behavior

Installed the extension, clicked 'Add Connection' -> 'Connection String', entered connection string 'mongodb://127.0.0.1:3001/meteor', got 'Unknown or unsupported transport “disabled” for address “disabled:”' error.

Mongodb instance is correctly running in my meteor app at the time, the connection string is correct (the default, checked it by `meteor mongo -U`)

#### Expected Behavior/Code

Should connect to my local mongodb.

#### Environment

- node.js / npm versions: node v12.20.1/npm 6.14.8
- OS: WSL2 (Ubuntu)

**Comment by Anemy** [comment]
Hi @PGlivicky tried to reproduce and was unable - I can connect to my local instance on w/ WSL 2.

This looks similar to https://github.com/microsoft/vscode-docker/issues/1411 - do you have credential storage/gnome-keyring setup on the wsl machine?
