### ISSUE TITLE
Unable to connect to mongodb via Mongogo VSCode on RaspberryPI4 Kali 64

### ISSUE THREAD

**Issue by fsebbah** [mongodb-js/vscode#254]
When trying to connect to a remote mongodb, I'm getting: Unable to load connection: Error: /usr/share/code/resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node: wrong ELF class: ELFCLASS32
 I'm running VS Code in Kali64 on raspberry PI 4.

#### Current Behavior
Installed the extension, clicked 'Add Connection' -> 'Connection String', entered connection string 'mongodb://192.168.1.10:3003/shop', got Unable to load connection: Error: /usr/share/code/resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node: wrong ELF class: ELFCLASS32

Mongodb instance is correctly running on the server at the time, the connection string is correct.

#### Environment

- node.js / npm versions: [e.g. node v15.4.0 / npm 7.0.5]
- OS: Linux kali64 4.19.118-Re4son-v8l+ #1 SMP PREEMPT Thu May 7 02:54:03 UTC 2020 aarch64 GNU/Linux

**Comment by Anemy** [comment]
Hi @fsebbah - thanks for reporting the issue - this looks like vscode is not able to access the credential storage on your system.

To fix this I think you have two options - you can make the extension not save any connections by updating the default storage location in the extension settings (screenshot) or you can try to make the credential storage usable by vscode/the extension. To make the credential storage work without erroring maybe installing [gnome-keyring](http://manpages.ubuntu.com/manpages/cosmic/man1/gnome-keyring-daemon.1.html#:~:text=The%20gnome%2Dkeyring%2Ddaemon%20is,tool%20to%20interact%20with%20it.) could fix the issue.
<img width="634" alt="Screen Shot 2021-02-18 at 4 03 31 PM" src="https://user-images.githubusercontent.com/1791149/108748197-9b5e4200-753e-11eb-82be-5f1525c93b66.png">
