### ISSUE TITLE
Option to modify/view advanced connection

### ISSUE THREAD

**Issue by MullinsN** [mongodb-js/vscode#258]
## Feature Request

Edit advanced connection string, instead of having to delete and recreate it because something isn't quite right.

## Detailed Description

While trying to add a connect to the M121 course database, and not having at the time the SRV connection string (sorted now). I was trying to make to establish a connect through the advanced connection, using the information in the following command.

**mongo "mongodb://cluster0-shard-00-00-jxeqq.mongodb.net:27017,cluster0-shard-00-01-jxeqq.mongodb.net:27017,cluster0-shard-00-02-jxeqq.mongodb.net:27017/aggregations?replicaSet=Cluster0-shard-0" --authenticationDatabase admin --ssl -u m121 -p aggregations --norc**

However, even though I could connect and view within VSC, I was running into a permissions problem when trying to run query's to test the connection. Which I was trying to resolve, but in the end lost the will to live, and tried to work out the SRV connection string.

**mongodb+srv://m121:aggregations@cluster0-jxeqq.mongodb.net/aggregations**

As with most things, easy when you know how.

## Context

This is an ease of use function.

## Possible Implementation

Make it available from connections panel, offer refresh of connection if a change is made.

**Comment by alenakhineika** [comment]
Looks like we have duplicate issues, so I am going to close this one. Please track progress here: https://github.com/mongodb-js/vscode/issues/282
