### ISSUE TITLE
Execution time of mongo shell versus playground 

### ISSUE THREAD

**Issue by MullinsN** [mongodb-js/vscode#262]
## Bug Report 
I have noticed that the time it takes the mongodb shell to return the same value is significantly shorter than running the same code in the playground.

#### Current Behavior

db.movies.aggregate([{
$match: {
  "imdb.rating": {$gte: 7} 
}
}]).itcount();

Takes approx. 17 seconds in the shell in VSC and DOS prompt, versus over 60 seconds in the Playground. I ran the test 3 - 4 times to be sure of the disparity.

#### Code/Gist

_db.movies.aggregate([{
$match: {
  "imdb.rating": {$gte: 7} 
}
}]).itcount();_

_mongo "mongodb://cluster0-shard-00-00-jxeqq.mongodb.net:27017,cluster0-shard-00-01-jxeqq.mongodb.net:27017,cluster0-shard-00-02-jxeqq.mongodb.net:27017/aggregations?replicaSet=Cluster0-shard-0" --authenticationDatabase admin --ssl -u m121 -p aggregations --norc_

OR

_mongodb+srv://m121:aggregations@cluster0-jxeqq.mongodb.net/aggregations_

#### Expected Behavior/Code

I suppose a similar execution time? It would be a real disadvantage to not be able to handle in a timely manner the same queries in the playground.

#### Environment

OS: Win10 20H2
Using v0.41 of the extension.

**Comment by Anemy** [comment]
The playgrounds are a bit of a wrapper around `mongosh`: https://github.com/mongodb-js/mongosh
The execution time of queries should perform in the same amount of time. The extension runs the shell commands in a separate process which also performs its own connection establishment - the discrepancy in execution time could lie there. I think we can keep this ticket open incase more people find it to be slow and then we can dig deeper into profiling where exactly things are taking longer.
