### ISSUE TITLE
Does not return all data from a query

### ISSUE THREAD

**Issue by ssnyder** [mongodb-js/vscode#273]
#### Current Behavior
Querying a collection to gather a count does not return all rows of results in the output view (on VSCode using latest version of extension).  This was verified by running the same query in Robo3T and the last record was missing from VSCode return.
#### Code/Gist
I am trying to count all of my documents, grouping by the payload.annotationLanguage value.  All records contain this field with a String value. 

db.bestdb.aggregate([{
    $group: {
        _id: {
            "lang": "$payload.annotationLanguage"
        },
        "count": {$sum:1}
    } 
},{
    $project: {
        "lang": "$_id.lang",
        "count": "$count",
        "_id": 0
    }
}]);

#### Expected Behavior/Code

I am expecting 21 records returned, but the last record is not returned by VSCode extension.  Running the same query in Robo3T provides all records expected.

#### Environment
- Connection to Mongo 3.2 server using admin user for authentication
- VSCode Help-About:

> Version: 1.53.2 (system setup)
> Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
> Date: 2021-02-11T11:48:04.245Z
> Electron: 11.2.1
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19042
>

**Comment by Anemy** [comment]
Hi @ssnyder this actually works as intended, currently unless `.toArray()` is specified we [open a cursor and fetch the first 20 documents, similar to the mongo shell](https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/). Thanks for reporting, I think we can probably improve how we show cursor playground results to users to help illustrate what they're seeing.

Does running 
```javascript
db.bestdb.aggregate([{
$group: {
_id: {
"lang": "$payload.annotationLanguage"
},
"count": {$sum:1}
}
},{
$project: {
"lang": "$_id.lang",
"count": "$count",
"_id": 0
}
}]).toArray();
```
Show all 21 results?

**Comment by ssnyder** [comment]
This does work thank you for the quick response.  I must have missed that in the docs.  

I have set the Mdb: default limit to 1000 in the settings.  This does not seem to be honored?  Also, setting the batch size (DBQuery.shellBatchSize=300) in the script being run (after the use, but before the aggregate) is also not being honored?  

I would appreciate more information on this in the docs and the playground default template as well.

**Comment by duard** [comment]
Same problem here, aways retrieve 20 records.

**Comment by eullercdr** [comment]
Same problem.

**Comment by Anemy** [comment]
@ssnyder Sorry the `mdb.defaultLimit` setting is for the documents shown in the explorer tree when a collection is opened. It does not impact playground results. 
I definitely agree that more information and documentation in the default playground template could help here, created https://jira.mongodb.org/browse/VSCODE-337 to track that. Thanks for mentioning that.

To change the amount of documents returned from a playground you can use a `$limit` stage in an aggregation, or a `.limit(30)` (where `30` is the amount of documents to return) along with the `.toArray()` mentioned in a previous comment.

For example, to return 25 documents:
```
db.bestdb.aggregate([{
  $group: {
    _id: {
      "lang": "$payload.annotationLanguage"
    },
    "count": {$sum:1}
  }
}, {
  $project: {
    "lang": "$_id.lang",
    "count": "$count",
    "_id": 0
  }
}, {
  $limit: 25
}]).toArray();
```

or 

```
db.bestdb.find({}).limit(25).toArray();
```
