### ISSUE TITLE
Feature Request: Add a code formater for playground 

### ISSUE THREAD

**Issue by Rohan-ult** [mongodb-js/vscode#280]

**Comment by alenakhineika** [comment]
Hey, please take a look at a similar issue that was previously opened: https://github.com/mongodb-js/vscode/issues/122
You can find a workaround there.

You also can vote for the requested feature in our (feedback forum)[https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/42380848-formatting-support-for-mongodb-playground-files] or create a new feature request if you like.

Thanks for reaching out and trying the extension!
