### ISSUE TITLE
Feature Request: Add ability to edit connection string

### ISSUE THREAD

**Issue by fritogotlayed** [mongodb-js/vscode#282]
Add ability to edit connection strings tracked by this extension

## Detailed Description

Adding the ability to edit an existing mongodb connection string could have a few boons for developers. One main reason is to be able to easily change passwords during password rotations. 

## Context

One project I am working on uses randomized passwords for local development. Another set of environments I connect to undergo quarterly password rotations for their landscapes. While I have a process that succeeds for password rotations it is cumbersome and a bit error prone due to the nature of the workflow.

Current Workflow: 

1. Find the connection in the "Connections" section of the GUI
1. Copy/Paste the connection string to a text editor where it can be tweaked
1. Update the password section of the copied connection string
1. Delete the existing connection in the GUI
1. Add a new connection using the copy/paste & edited connection string

Proposed Workflow:

1. Find the connection in the "Connections" section of the GUI
1. Select "Edit" for the connection string
1. Update the connection string password
1. Save the connection string

## Possible Implementation

N/A: I've been meaning to look at the extension code and submit a PR but have not yet had time to familiarize myself with the code.

**Comment by alenakhineika** [comment]
Hey, can you create a feature request in our [feedback forum](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code)?

**Comment by alenakhineika** [comment]
Use the following ticket to track the progress: [VSCODE-406](https://jira.mongodb.org/browse/VSCODE-406).

**Comment by alenakhineika** [comment]
The feature was shipped with the [v1.5.0](https://github.com/mongodb-js/vscode/releases/tag/v1.5.0) release.
