### ISSUE TITLE
"Mdb: Shell" option selection not working?

### ISSUE THREAD

**Issue by wcwhitehead** [mongodb-js/vscode#286]
I executed some mapReduce code in the beta mongosh that causes an error ("Unable to handle 'this' keyword outside of method definition"), however, executing it in the old mongo shell works just fine. When I try to execute this code in VS Code in a Mongo Playground, I get the same error, which, to me means the beta mongosh shell is being used. I checked my settings and I am set to use the old mongo shell. Is the extension not reading the correct option to execute code through the specified shell? I'm on Windows 10, running Mongo on Windows 10 (not WSL).

**Comment by alenakhineika** [comment]
Hey, the MongoDB playgrounds are built on top of `mongosh`, this is not what you can change with VSCode settings. The settings can change shell for VSCosde terminal though. The old shell can not be embedded into web applications e.g. VSCode playgrounds or Compass, and this is why we built `mongosh`. Sorry that currently you are receiving this error. We are actively working on the complete API support, when `mongosh`  goes GA you will get all features compatible with the old shell.
