### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DominicGit1** [mongodb-js/vscode#289]
## Bug Report
Can't print out the queries to the console log, only prints [Object object]
#### Current Behavior
I have tried several different methods I've found people suggest, like console.log() but no matter what I do it always prints [object Object], or gives me a error saying tojson is undefined.
db.therapists.find().forEach(print); and db.therapists.find().forEach(printjson) both give me
[object Object]
[object Object]
[object Object]

require('util').inspect.defaultOptions.depth = null
printjson(db.sessions.find())
gives me
[object Object],[object Object],[object Object]
and
var myCursor = db.sessions.find( )
var myDocument = myCursor.hasNext() ? myCursor.next() : null
if (myDocument) {
    var myName = myDocument.name
    print (tojson(myName))
}
gives me "tojson is not defined".
I have even opened the generic mongodb playground template and did 
print({a: 'foo', b: 'bar'})
which still printed out [object Object]

#### Code/Gist
db.sessions.insertMany([//i just set each therapist to be in a session with their corresponding patient who holds the same id number
  {'therapist_id': t_id1,'patient_number_id': p_id1,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 1},
  {'therapist_id': t_id2,'patient_number_id': p_id2,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 2},
  {'therapist_id': t_id3,'patient_number_id': p_id3,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 3},
])
is my small table. the t_id and p_id are just ObjectId()s I generate to help connect my initial making of my tables,

#### Expected Behavior/Code
Just want it to actually print out my queries inside the console.

#### Environment

- node.js / npm versions: 12.18.3
- OS: Windows_NT x64 10.0.19042

**Comment by alenakhineika** [comment]
Hey, using your example, this is how you can print documents with `util` module:

```
const util = require('util');

db.sessions.insertMany([
  { 'therapist_id': 1,'patient_number_id': 1,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 1 },
  { 'therapist_id': 2,'patient_number_id': 2,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 2 },
  { 'therapist_id': 3,'patient_number_id': 3,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 3 },
]);

const myCursor = db.sessions.find( )
const myDocument = myCursor.hasNext() ? myCursor.next() : null;

console.log(`${util.inspect(myDocument)}`);
```

Please let me know how it worked for you!

**Comment by DominicGit1** [comment]
> ```js
> const myCursor = db.sessions.find();
> const myDocument = myCursor.hasNext() ? myCursor.next() : null;
> 
> console.log(`${util.inspect(myDocument)}`);
> ```

Thanks a lot, it worked like a charm!
![image](https://user-images.githubusercontent.com/71572047/115747460-e805a400-a35a-11eb-8e54-40b877013e6f.png)

**Comment by DominicGit1** [comment]
> Hey, using your example, this is how you can print documents with `util` module:
> 
> ```js
> const util = require('util');
> 
> db.sessions.insertMany([
>   { 'therapist_id': 1,'patient_number_id': 1,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 1 },
>   { 'therapist_id': 2,'patient_number_id': 2,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 2 },
>   { 'therapist_id': 3,'patient_number_id': 3,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 3 },
> ]);
> 
> const myCursor = db.sessions.find();
> const myDocument = myCursor.hasNext() ? myCursor.next() : null;
> 
> console.log(`${util.inspect(myDocument)}`);
> ```
> 
> Please let me know how it worked for you!

Actually, should it only be printing out the first result from the collection?

**Comment by alenakhineika** [comment]
If you use `myCursor.next()` it iterates through results and prints one document at a time.

```js
const util = require('util');

db.sessions.insertMany([
  { 'therapist_id': 1,'patient_number_id': 1,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 1 },
  { 'therapist_id': 2,'patient_number_id': 2,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 2 },
  { 'therapist_id': 3,'patient_number_id': 3,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 3 },
]);

const myCursor = db.sessions.find();

console.log(`${util.inspect(myCursor.next())}`); // therapist_id: 1
console.log(`${util.inspect(myCursor.next())}`); // therapist_id: 2
console.log(`${util.inspect(myCursor.next())}`); // therapist_id: 3
```

**Comment by DominicGit1** [comment]
> If you use `myCursor.next()` it iterates through results and prints one document at a time.
> 
> ```js
> const util = require('util');
> 
> db.sessions.insertMany([
>   { 'therapist_id': 1,'patient_number_id': 1,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 1 },
>   { 'therapist_id': 2,'patient_number_id': 2,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 2 },
>   { 'therapist_id': 3,'patient_number_id': 3,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 3 },
> ]);
> 
> const myCursor = db.sessions.find();
> 
> console.log(`${util.inspect(myCursor.next())}`); // therapist_id: 1
> console.log(`${util.inspect(myCursor.next())}`); // therapist_id: 2
> console.log(`${util.inspect(myCursor.next())}`); // therapist_id: 3
> ```

Oh got it. In that case however, how does one know how many console.logs one should do to show all the documents that came from the query?

**Comment by alenakhineika** [comment]
You can find all possible options here in the documentation: https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/

You can convert your cursor to the array or use `forEach` on the cursor itself.

```js
const util = require('util');

db.sessions.insertMany([
  { 'therapist_id': 1,'patient_number_id': 1,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 1 },
  { 'therapist_id': 2,'patient_number_id': 2,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 2 },
  { 'therapist_id': 3,'patient_number_id': 3,'Session_Date': new Date(),'Session_Length': '2 hours','Session_number': 3 },
]);

const myCursor = db.sessions.find();

console.log(`${util.inspect(myCursor.toArray())}`);

myCursor.forEach((doc) => { console.log(`${util.inspect(doc)}`); });
```
