### ISSUE TITLE
Bug - Changing through dbs

### ISSUE THREAD

**Issue by gabrielDonnantuoni** [mongodb-js/vscode#291]
First of all, thank you a lot for this Extension!

#### Current Behavior
With an open playground if you run a "selected from playground" with:
`use('nameDB');` you will receive an expected message like `switched to db nameDB`
but when you run `db;` to see the used database it isn't updated.

![image](https://user-images.githubusercontent.com/71512765/116499974-e4ef4400-a883-11eb-8dbe-2a17982dabd5.png)
![image](https://user-images.githubusercontent.com/71512765/116500020-00f2e580-a884-11eb-97b1-99c530d74d8c.png)

The extension works great when you run All, with no selection.

#### Expected Behavior/Code
Is expected to change correctly the db.

**Comment by Anemy** [comment]
@gabrielDonnantuoni If I'm understanding correctly, that behavior should be expected. When running a selection with just the `db` command it should default to the `test` db unless there's an explicit `use` db command. Going to close this issue for now if that's alright. Feel free to reopen.
