### ISSUE TITLE
Bug Report "t is not a constructor"

### ISSUE THREAD

**Issue by maxidev** [mongodb-js/vscode#295]
#### Current Behavior

Can't connect to localhost or SSH tunnel, error msg (see below) "t is not a constructor"

#### Expected Behavior/Code

Properly connect to local or remote instance.

#### Environment

- node.js / npm versions: 
- same error with node version 12 or 14
- OS: Linux Mint 20.1

#### Additional Context/Screenshots

![image](https://user-images.githubusercontent.com/5783552/120234222-e7034480-c22d-11eb-8db4-6665ac1f25fd.png)

VSCode details:

![image](https://user-images.githubusercontent.com/5783552/120234370-2f226700-c22e-11eb-9517-a37944f273b4.png)

**Comment by Anemy** [comment]
Hi @maxidev - sorry this is happening. Are you able to connect with a connection string? 
<img width="474" alt="Screen Shot 2021-06-03 at 8 59 19 AM" src="https://user-images.githubusercontent.com/1791149/120648749-fd85e780-c449-11eb-884c-27a3da93b1f2.png">
This might be an issue with how we handle things on linux machines.

**Comment by maxidev** [comment]
Hi Anemy, thanks for your response.

When using connection string I get:
![image](https://user-images.githubusercontent.com/5783552/120674949-fe7b4100-c46a-11eb-9a7b-001eac1980fe.png)

**Comment by maxidev** [comment]
Let me know if I can help by providing additional info or testing something

**Comment by alenakhineika** [comment]
I've opened a JIRA ticket so you can track progress here: https://jira.mongodb.org/browse/VSCODE-275

**Comment by Anemy** [comment]
@maxidev In the most recent release we've updated our connection logic and MongoDB node driver. Could you see if this issue still persists? I haven't been able to reproduce yet, so any additional information helps, was the local instance you tried to connect to without authentication?

**Comment by alenakhineika** [comment]
Closing the issue. Feel free to reopen it if you encounter the problem again.
