### ISSUE TITLE
Feature Request -Add the ability to use environment variables

### ISSUE THREAD

**Issue by kildarr** [mongodb-js/vscode#299]
## Feature Request
Add the ability to use environment variables
## Detailed Description
Add the ability to use environment variables in the settings.json like many other extensions

Having the ability to execute queries in multiple environments, i.e. dev, qa, uat for example embedded in my queries and or connection strings.

**Comment by Anemy** [comment]
@kildarr I'm not quite sure I understand how this feature could look, could you walk us through the use case for this? Does this feature involve using a settings.json within the current workspace to populate the connections that the extension loads?

We have a feedback forum which might be a good place for this (it has upvoting and helps us organize and understand demand for features: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code )

Thanks for checking out the extension!
