### ISSUE TITLE
Can't view output in Terminal 

### ISSUE THREAD

**Issue by myselfsrk** [mongodb-js/vscode#305]
After executing the script, i can only see output in Playground results tab but not in the Playground output tab ( Terminal).

**Comment by Anemy** [comment]
Hi @myselfsrk - if I understand correctly I believe that's intended. The playground output tab in the terminal is reserved for logs from the script. If you run `console.log('test');` you should see `test` in the terminal. Feel free to reopen if you're thinking of something else.

**Comment by myselfsrk** [comment]
Hello, 

I couldn't get any output in the Terminal output window. Although i have executed the log command. Please find the screenshot.

![image](https://user-images.githubusercontent.com/23332011/123506619-c4c0e300-d682-11eb-90de-0b8bf1afcb9f.png)

**Comment by addaleax** [comment]
@myselfsrk I think this goes away if you write `use('aggregations');` instead of `use aggregations`, because in the latter case, the VSCode extension thinks the entire script is just one long `use` call – I agree, this is surprising and we should probably do something about this. (To be fair, the MongoDB server *does* allow newlines in database names.)

I’ve opened https://jira.mongodb.org/browse/VSCODE-267 to track this on our side.

**Comment by myselfsrk** [comment]
@addaleax Still same no output in the Terminal tab. 
![image](https://user-images.githubusercontent.com/23332011/123513831-0c5c6480-d6ad-11eb-9a3f-38724d94d632.png)

**Comment by addaleax** [comment]
@myselfsrk Yeah, it’s especially confusing that the space after `use` makes a difference here, but it was intentional that I wrote `use('aggregations')` (without the space) :slightly_smiling_face:

**Comment by myselfsrk** [comment]
Yeah Thanks, it worked, but it is not as expected. I can't get output like "switched to db" or findOne query output in the terminal. Does that shows or it isn't.

**Comment by addaleax** [comment]
@myselfsrk If you want to print something to the terminal here, then yeah, you’ll want to use `console.log()` explicitly. VSCode will only give you the result of the last statement in the playground output, and only show things in the terminal that have been sent there explicitly.
