### ISSUE TITLE
Too much slow

### ISSUE THREAD

**Issue by ats1999** [mongodb-js/vscode#320]
## Feature Request
The extensions work perfectly, but speed is  much slower. If we connect mongo shell from terminal, then it returns the result in just few milli seconds, but this extension takes 2-3 seconds. 

## Context
This change will improve the productivity of the user.

**Comment by Anemy** [comment]
Hi @ats1999 - just to clarify, running a playground is what is taking some time?
I think the improvement might better suited for our feedback forum which allows for upvoting issues so we can better gauge how impactful a potential change is: [feedback forum](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/) 
Thanks for opening the issue and we're happy the extension is working smoothly despite the slowness :)

**Comment by wxs77577** [comment]
Same problem here, executing the same query in vscode mongodb plugin is much slower than robo 3t or mongodb shell.
