### ISSUE TITLE
Bug Report: SSL file path on Ubuntu

### ISSUE THREAD

**Issue by vteran93** [mongodb-js/vscode#346]
Trying to connect with SSL config takes a wrong path
#### Current Behavior

When you try to create a connection with SSL certificate, and you select the *.pem file in the server validation section you get a wrong path in the file field. 

![image](https://user-images.githubusercontent.com/1650359/134559902-7a2136c6-c0ba-4870-8f43-1ce7627ab218.png)

After put all the connection values, you get 
![image](https://user-images.githubusercontent.com/1650359/134560112-72a06ec9-d6f5-4676-8c9b-58b51c5db340.png)

#### Expected Behavior/Code

You should get the correct path to the selected file.
You should be able to connect to the server 

#### Environment

- node.js / npm versions:
- OS:  Ubuntu 20.04.3 LTS x86_64 
- vscode: 1.60.1 83bd43bc519d15e50c4272c6cf5c1479df196a4d x64
- Mongo DB for vscode : v0.6.10
- Node v14.17.6.
- npm@6.14.15

**Comment by Anemy** [comment]
Hi @vteran93 - thanks for reporting - this fix should be in https://github.com/mongodb-js/vscode/pull/343 and will be in the next release. I'll verify it fixes it on dev tomorrow once the ubuntu image for virtual box finishes downloading 😅 
If it's alright I'll leave this open and close it once the release is live.

**Comment by Anemy** [comment]
https://github.com/mongodb-js/vscode/releases/tag/v0.6.12 v0.6.12 is released with the fix - thanks again for reporting! Feel free to reopen if you update and it doesn't behave as expected.
