### ISSUE TITLE
Executing query in MongoDB Playground fails with error "ENAMETOOLONG: name too long, open '-----BEGIN CERTIFICATE----- ..."

### ISSUE THREAD

**Issue by grzegorz-swirski** [mongodb-js/vscode#349]
Issue Type: <b>Bug</b>

1. Connect to DocumentDB database (AWS) using form
- Connection type: Standalone, use correct hostname and port
- Authentication Username/Password, use correct credentials
- switch to SSL/TLS tab, choose Server Validation, provide official CA file 
(can be downloaded from https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem)
2. Connection is successful (collections and documents are visible in "CONNECTIONS" tab)
3. Go to playground, execute any command

Expected: results of the query are shown
Actual: The following error appears and no results are shown:

ENAMETOOLONG: name too long, open '-----BEGIN CERTIFICATE----- MIIEBzCCAu+gAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgZQxCzAJBgNVBAYTAlVT(...)

Extension version: 0.6.10
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:01:43.795Z)
OS version: Linux x64 5.11.0-37-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|30.97GB (13.98GB free)|
|Process Argv|--unity-launch --crash-reporter-id 895f4f3f-fa66-4bae-8937-0c16a5c4a473|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30370836
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis400:30374798

```

</details>

**Comment by mmarcon** [comment]
Hi @grzegorz-swirski. Thank you for reporting the problem.

While we typically do not prioritize fixes for DocumentDB, we recently made a fix (#347) that may solve this problem too. We are planning to release a new version with this fix soon.

**Comment by grzegorz-swirski** [comment]
Thank you @mmarcon . BTW is DocumentDB officially supported by the extension?

**Comment by mmarcon** [comment]
No, it's not.

DocumentDB only supports a small subset of the MongoDB functionality / APIs so it's reasonable to think that some things may break.

**Comment by Anemy** [comment]
Hi @grzegorz-swirski - just following up - v0.6.12 is released https://github.com/mongodb-js/vscode/releases/tag/v0.6.12 with the fix. Thanks for reporting the issue! Feel free to reopen if you update and it doesn't behave as expected.
