### ISSUE TITLE
Retryable writes are not supported

### ISSUE THREAD

**Issue by diegoleme** [mongodb-js/vscode#351]
## Feature Request

I want to configure the `retryWrites`

## Detailed Description

Today I get the following error: `Retryable writes are not supported`. And the parameter `retryWrites=false` solves this problem

**Comment by addaleax** [comment]
@diegoleme Can you share exact steps to reproduce? :slightly_smiling_face:

**Comment by diegoleme** [comment]
@addaleax I add `&tlsAllowInvalidHostnames=true&tlsCAFile=filename` and percent-escape the filename.

Using mongosh I can connect via command line with this URL, but it gives an error using the `Connect with connection string`. 

Can I debug somehow?

**Comment by diegoleme** [comment]
@addaleax The `Failed to connect` error appears on the output panel.

**Comment by alenakhineika** [comment]
Hey, @diegoleme could you please try the latest version of the extension and let us know if the issue is gone or remains?

**Comment by alenakhineika** [comment]
Closing the issue because of lack of activity. Feel free to reopen if the problem persists.
