### ISSUE TITLE
Connection through X.509 doesn't work.

### ISSUE THREAD

**Issue by bambrozio** [mongodb-js/vscode#361]
Issue Type: <b>Bug</b>

Hi,
I have a [Shared Atlas MongoDB sandbox](https://www.mongodb.com/pricing) that I can successfully connect MongoDB for VS Code extension through user and password (SCRAM). However, I cannot connect through X.509 authentication method.

I have tried using both "connection string" option and filling out the "advanced connection settings" form. Yet, none of them works when using X.509 methods.

VS Code keep raising the error: `Unable to resolve your shell environment in a reasonable time. Please review your shell configuration.` whenever I try to establish the connection.

Here's the connection string I'm using:

```
mongodb+srv://<subdomain>.<domain>.mongodb.net/test-db?authSource=%24external&authMechanism=MONGODB-X509&tls=true&tlsCertificateKeyFile=/path/to/X509-cert.pem
```

In order to make sure the connection string is valid, I successfully used it to connect to my database using [Mongoose](https://mongoosejs.com/).

Please, let me know if you need more info to help troubleshooting.

Thanks in advance!
Bruno.

Extension version: 0.6.12
VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:58.853Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by Anemy** [comment]
Going to close this issue, feel free to reopen if there's more information. Was able to successfully connect using x.509. Thanks for checking out the extension and opening the issue.
