### ISSUE TITLE
"command 'mdb.saveMongoDBDocument' not found" when saving changes of package.json

### ISSUE THREAD

**Issue by foreverpinetree** [mongodb-js/vscode#367]
I use vscode to edit **package.json**, it's fine untill I installed mongodb extension. When I click "ctrl+s" to save the changes, a message box pops up: "**command 'mdb.saveMongoDBDocument' not found**", and it prevents me to save the changes.

It only occurs on editing package.json, don't have problem when dealing with other files, it's strange.

**Comment by Anemy** [comment]
Hi @foreverpinetree - here's a jira issue to track this bug: https://jira.mongodb.org/browse/VSCODE-303 thanks for reporting, hopefully we can get a fix out to you soon

**Comment by foreverpinetree** [comment]
OK, thank you.

**Comment by foreverpinetree** [comment]
> Hi @foreverpinetree - here's a jira issue to track this bug: https://jira.mongodb.org/browse/VSCODE-303 thanks for reporting, hopefully we can get a fix out to you soon. I haven't been able to reproduce this yet, so any additional information helps.

OK, thank you.
