### ISSUE TITLE
Bug Report: Tries to use Node.js version from package.json

### ISSUE THREAD

**Issue by LinusU** [mongodb-js/vscode#375]
#### Current Behavior

I recently updated our `browserslist` field in our `package.json` to read `Node 14.18`. Now this VS Code plugin cannot run anymore. I get the following error when trying to run a query:

> Unknown version 14.18 of Node.js

I can only guess that for some reason one of the tools is picking up my local Browserslist configuration?

#### Code/Gist

n/a

#### Expected Behavior/Code

For it to run the query without error...

#### Environment

- node.js / npm versions: v16.11.1 / v8.0.0
- OS: macOS Monterey 12.0.1

#### Possible Solution

n/a

#### Additional Context/Screenshots

<img width="484" alt="Screenshot 2021-12-07 at 11 19 05" src="https://user-images.githubusercontent.com/189580/145011136-fea4ced9-ea46-4088-9f18-03c5969348bc.png">

**Comment by Anemy** [comment]
Hi @LinusU - thanks for reporting, we've been able to reproduce this. I've opened https://jira.mongodb.org/browse/VSCODE-315 to help track this, hopefully we can get a fix out soon.

**Comment by LinusU** [comment]
@Anemy seems like the blocking issue (https://jira.mongodb.org/browse/MONGOSH-1085) was fixed in mongodb-js/mongosh#1176, and the update was merged in #385. Thanks everyone involved for the work!

Is there any timeline for when this will be released?

**Comment by Anemy** [comment]
@LinusU thanks for the ping - this was in the [0.9.2 release](https://github.com/mongodb-js/vscode/releases) yesterday. Thanks again for bringing it up!
