### ISSUE TITLE
How to remove comments of snippet

### ISSUE THREAD

**Issue by zlee520** [mongodb-js/vscode#382]
{/**
   * path: Path to the array field.
   * includeArrayIndex: Optional name for index.
   * preserveNullAndEmptyArrays: Optional
   *   toggle to unwind null and empty values.
   */
  $unwind: {
    path: path,
    includeArrayIndex: 'string',
    preserveNullAndEmptyArrays: boolean
  }}

**Comment by alenakhineika** [comment]
Hey, thank you for reaching out and for trying the extension! Currently, there is no such setting to disable comments in snippets. We already have a similar request on our [feedback forum](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/40686811-option-to-disable-comments-for-aggregation-stages). You can vote for it and track progress there.

**Comment by zlee520** [comment]
I've solved it
edit the file  c:\user\yourname\.vscode\extensions\mongodb.mongodb-vscode-0.9.3\snippets\stage-autocompleter.json
and remove the comments

**Comment by alenakhineika** [comment]
Hey, with the v0.11.1 version of the extension we shipped the IntelliSense improvements, which include replacing previously existing snippets with autocomplete for aggregation stages and operators. Now we do not insert documentation blocks directly into the playground. Instead, when selecting a stage from the suggestions list you can find a hint on what the operator does and a link to the online documentation.
