### ISSUE TITLE
Improperly encoded URI does not give an error

### ISSUE THREAD

**Issue by cradaydg** [mongodb-js/vscode#383]
Passwords in a connection string that contain special characters such as # that are not uri encoded fails to connect with no error message.

In MongoDB Compass, this results in an error, before a connection is attempted.

Invalid URL: mongodb+srv://username:yada#@blah.6tsgn.mongodb.net/....

Further, in the specific case of the # character replaced with %23 results in an authorization error.

**Comment by alenakhineika** [comment]
Hey, which version of the extension do you use? I am trying to use your URI and I can see a validation message with information about unescaped characters.

<img width="694" alt="Screenshot 2022-01-19 at 13 39 20" src="https://user-images.githubusercontent.com/16307679/150132734-bbb36c11-60cd-41c6-860c-78509f675982.png">

**Comment by cradaydg** [comment]
0.7 MongoDB for VSCode

![image](https://user-images.githubusercontent.com/17388487/150146976-d9473ede-9886-4c30-bdb2-eb222a49995b.png)

**Comment by cradaydg** [comment]
or do I have the wrong place to report this?

**Comment by alenakhineika** [comment]
Ah thank you very much for checking the version! And this is absolutely the right place to report such issues :)

You are right, I can reproduce this problem on 0.7. We are going to release 0.8 pretty soon where this problem is fixed. I will message here when the realize is published, so you can try it out.

Thank you for trying the extension and creating the issue!

**Comment by cradaydg** [comment]
I found there is something else too, VS Code wouldn't accept a valid URI until I restarted it.
Is there a log somewhere to look at when odd things happen?

**Comment by alenakhineika** [comment]
We have just [published the 0.8.0 release](https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode) that should solve your first issue! Could you please try it out and check maybe it also solved the second one as well :) let me know how it went!

You can see some logs of the extension in the output channel -> mongodb. Hope this helps!

<img width="1060" alt="Screenshot 2022-01-19 at 17 48 10" src="https://user-images.githubusercontent.com/16307679/150176418-3941c999-62e8-435b-87f2-13a39dcbcfc3.png">

**Comment by cradaydg** [comment]
![image](https://user-images.githubusercontent.com/17388487/150177565-8e5a8488-a5fe-4185-a6fe-523233a5a201.png)

Looks good to me. I had changed the password, without the #, so I was getting an authentication error. Forgot I had done that.

**Comment by cradaydg** [comment]
Looks good to me. Can't say about the oddity with restarting VS Code. Hard to tell why that was happening.

**Comment by alenakhineika** [comment]
Thanks for testing it on your end! I am closing the ticket for now, but feel free to reopen or create a new one if you notice this oddity with restarting VSCode again.
