### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bertellig** [mongodb-js/vscode#421]
- Issue Type: `Performance`
- Extension Name: `mongodb-vscode`
- Extension Version: `0.9.3`
- OS Version: `Darwin x64 21.4.0`
- VS Code version: `1.67.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/vy/xsk_h5354jsbglmzvxf3k4cw0000gn/T/mongodb.mongodb-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mmarcon** [comment]
@bertellig what were you doing when you experienced the high CPU load?

**Comment by mmarcon** [comment]
We don't have enough information to understand what is going on.
