### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Eyob-bob** [mongodb-js/vscode#431]
please add the remove button for the cluster.

**Comment by Anemy** [comment]
Hi @Eyob-bob a saved connection can be removed with the right click contextual menu. Does that do what you're looking for?
![Screen Shot 2022-07-20 at 4 39 01 PM](https://user-images.githubusercontent.com/1791149/180077367-692fd6b7-fd57-420d-8988-be4f15cd1323.png)

**Comment by Eyob-bob** [comment]
ya ya ya   Thank you so much
