### ISSUE TITLE
Is there any option in Settings to show more than 20 Documents in query ?

### ISSUE THREAD

**Issue by DGamer007** [mongodb-js/vscode#435]
## Is there any option in Settings to show more than 20 documents in Query ?
I am trying to run a query using this Extension in VS Code. The query is simple **find** query. 
`db.users.find({})`

This query is supposed to show 30 records but it is showing only 20. Now, I found this configuration `config.set('displayBatchSize',200)` on Internet but It isn't working in VS Code. Is there any workaround for this ? I would love if this thing becomes a part of VS Code settings for this extension.

Also, I don't have `mongosh` installed on my machine but I dont think it is a problem for using MongoDB for VS Code extension 'coz queries run just fine.

**Comment by addaleax** [comment]
This isn’t a direct answer to your question, but is your goal to get *all* results? In that case, you probably want `db.users.find({}).toArray()`, not a different batch size.

**Comment by DGamer007** [comment]
Yeah, that worked. Thank you so much.

**Comment by JigarRajput** [comment]
db.users.find({}).limit(30)
