### ISSUE TITLE
Feature Request: AWS IAM authentication in connection form

### ISSUE THREAD

**Issue by wickdninja** [mongodb-js/vscode#444]
## Detailed Description

Add support for AWS IAM authentication ( outside constructing the connection string myself ) 
e.g. accept and encode AWS credentials and add them to the connection string for me like Compass does.
![CleanShot 2022-10-20 at 10 36 36](https://user-images.githubusercontent.com/6932589/196979286-19202394-8b70-404a-bd9e-5f93d1e845c5.png)

## Context

This feature is preventing my team from adopting this over using Compass as their daily DB tool.

**Comment by alenakhineika** [comment]
The feature was shipped with the [v1.5.0](https://github.com/mongodb-js/vscode/releases/tag/v1.5.0) release.
