### ISSUE TITLE
Run selected lines is not working 

### ISSUE THREAD

**Issue by vbaswin** [mongodb-js/vscode#447]
When pressing run selected lines from command palette it is not working.
But run all is working perfectly fine.

<img width="1470" alt="Screenshot 2022-10-30 at 19 15 23" src="https://user-images.githubusercontent.com/88179338/198881872-3d8f726b-6f1d-4c3d-b86a-47a592e75c3d.png">

We can see that the command on run does not delete the record with _id: 3

These actions work perfectly fine with the command line.
The extension is superb with it's intellisense so just want you guys to improve.

Thanks in advance for such a superb integration of mongo with vscode :)

**Comment by gribnoysup** [comment]
Hey @vbaswin, when running selected code, `use(<your db>)` needs to be part of the selection to make sure you are running your command against an expected database, otherwise you are running the command against default database (which is usually test)

**Comment by vbaswin** [comment]
Thankyou so much @gribnoysup
Now it is working perfectly fine🤝
