### ISSUE TITLE
Feature Request support require module in playground

### ISSUE THREAD

**Issue by whiter001** [mongodb-js/vscode#449]
Cannot find module 'dayjs' Require stack:  `~/extensions/mongodb.mongodb-vscode-0.9.5/dist/languageServerWorker.js`

but can run with `mongosh -f ./.mongodb`

**Comment by mmarcon** [comment]
HI @whiter001.

It's actually possible to use `require` to use modules installed from npm. You need, however, to install them at [one of the locations where VS Code looks for them](https://www.mongodb.com/docs/mongodb-vscode/require-modules/) so from this perspective the VS Code is a bit less flexible than `mongosh`.

**Comment by alenakhineika** [comment]
Closing the ticket. Feel free to reopen if you encounter the issue again!
