### ISSUE TITLE
Use Prettier to format mongodb files.

### ISSUE THREAD

**Issue by moisesbites** [mongodb-js/vscode#450]
Use Prettier to format mongodb files.

## Context

Many scripts are used to modify databases in production mode, writing those on databases in test mode. Other way, many big scripts were written  to build reports. It's good to format these files.

**Comment by alenakhineika** [comment]
Hey, thank you for reaching out! This work is actually planned by our team. We are going to improve autocomplete and support integration with ESLint or prettier. As soon as we have a ticket to track the progress, I post it here for your reference!

**Comment by moisesbites** [comment]
Ok. Thank you.

**Comment by alenakhineika** [comment]
Hey, in the v0.11.1 version of the extension playgrounds became proper JavaScript environments and now support such JavaScript language features as syntax highlighting, variable, function, and expression autocomplete, code refactoring and formatting, and linting. Hope these updates enhance your workflow!
