### ISSUE TITLE
Extension keeps creating new stray untitled files

### ISSUE THREAD

**Issue by matter-it-does** [mongodb-js/vscode#466]
Without any reason, I keep seeing new untitled files being created which need confirmation to be closed. Annoying.

**Comment by Anemy** [comment]
Looks like this happens with unsaved playground files. Created a ticket in our jira to track this: https://jira.mongodb.org/browse/VSCODE-360
If you'd like you can add yourself as a watcher to that to get email notifications when the bug fixed (we'll also close this).

Thanks for reporting the issue!

**Comment by alenakhineika** [comment]
The issue is not reproducible anymore. Feel free to reopen if you encounter the same issue.
