### ISSUE TITLE
Bug Report: Connections not storing on linux with credential store

### ISSUE THREAD

**Issue by M-Gonzalo** [mongodb-js/vscode#476]
#### Current Behavior

Connections are not saved, either locally or globally. A reload or restart of the ID deletes everything

#### Environment

- node.js / npm versions:
	- Linux 6.1.8-arch1-1 
	- Plasma 5.26.5 
	- node v16.18.1

**Comment by Anemy** [comment]
@M-Gonzalo It might be that VSCode is not able to access the credential storage on your system.

To fix this I think you can try to make the credential storage usable by VSCode/the extension. To make the credential storage work without erroring, installing [gnome-keyring](http://manpages.ubuntu.com/manpages/cosmic/man1/gnome-keyring-daemon.1.html#:~:text=The%20gnome%2Dkeyring%2Ddaemon%20is,tool%20to%20interact%20with%20it.) might fix the issue.

Closing this, feel free to reopen if you do have a credential storage on your system that the extension has access to.

**Comment by M-Gonzalo** [comment]
> @M-Gonzalo It might be that VSCode is not able to access the credential storage on your system.
> 
> To fix this I think you can try to make the credential storage usable by VSCode/the extension. To make the credential storage work without erroring, installing [gnome-keyring](http://manpages.ubuntu.com/manpages/cosmic/man1/gnome-keyring-daemon.1.html#:~:text=The%20gnome%2Dkeyring%2Ddaemon%20is,tool%20to%20interact%20with%20it.) might fix the issue.
> 
> Closing this, feel free to reopen if you do have a credential storage on your system that the extension has access to.

I'm on KDE, it has its own credential storage system. I can use any other extensions that might need to store something, including some with API keys or those that need to login somewhere first

**Comment by alenakhineika** [comment]
Hey @M-Gonzalo, we release a new 1.1.0 version of the extension, that includes migration secrets from keytar to SecretStorage. See the [release notes](https://github.com/mongodb-js/vscode/releases/tag/v1.1.0) for more details. Please try the new version and let us know if this solves the issue of storing connections for you.

**Comment by M-Gonzalo** [comment]
> 

Thanks. I found out that the problem only happens when I configure the extension to ask where to store the credentials. Not if I leave the default settings. That's how I've been managing for now. Might help to reproduce the issue somewhere else

**Comment by alenakhineika** [comment]
This is incredibly helpful! ❤️ I was just able to reproduce it. Will look into what causes it, thank you very much! Please use this ticket to track the progress: https://jira.mongodb.org/browse/VSCODE-423. Those two issues are for sure connected :)

**Comment by alenakhineika** [comment]
Hey, the fix was shipped with the [v1.5.0](https://github.com/mongodb-js/vscode/releases/tag/v1.5.0) release. Closing the issue, but feel free to reopen if the problem persists for you.
