### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Vipinkumarpatel-8423** [mongodb-js/vscode#483]
- Issue Type: `Performance`
- Extension Name: `mongodb-vscode`
- Extension Version: `0.10.0`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.75.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Atul/AppData/Local/Temp/mongodb.mongodb-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by alenakhineika** [comment]
Hey, could you please tell us which process caught your attention in your performance profile?

**Comment by alenakhineika** [comment]
Closing the issue. Feel free to re-open if this is still relevant and you have particular profile details to share.
