### ISSUE TITLE
Bug Report: The whole thing is suddenly not working

### ISSUE THREAD

**Issue by Mortis66666** [mongodb-js/vscode#506]
#### Current Behavior

When I click on a connection it just changed the direction of > to down and displaying nothing below, I still can connect it with code and still can do stuff in the mongodb dashboard, it also shows a notification of connection successful and immediately shows disconnected.

#### Expected Behavior/Code

To show tree of database and collections

#### Environment

- node: 16.13.1
- npm: 8.12.2
- OS: Windows 10

#### Additional Context/Screenshots
![image](https://user-images.githubusercontent.com/87415361/229049504-0ca47f61-35da-40d8-8651-5f7f3e758d6d.png)

![image](https://user-images.githubusercontent.com/87415361/229049227-6cd1c146-4f94-4258-85cb-d92a74c82faf.png)

**Comment by alenakhineika** [comment]
Hey, could you please share with us:
- are you connecting to a standalone cluster or some other configuration?
- what OS are you using?
- what version of the extension is it?
- and what is your current VSCode version?

**Comment by Mortis66666** [comment]
I'm using VS Code version 1.77.0 and extension version v0.11.1. I've updated the OS version in the comment above. I'm not sure if it's a standalone cluster. However, it fixed itself after reloading VS Code multiple times. I saw a 'Reload Required' button beside the extension and clicked it. It worked normally like before after that.

**Comment by alenakhineika** [comment]
We released a new version of VSCode an hour after you opened the issue, that is why it was mysteriously solved by itself and asked you to reload :) My guess is that you experienced a problem described in [this PR](https://github.com/mongodb-js/vscode/pull/505) and we shipped the fix in the v0.11.1 release.

Thanks for reporting and feel free to re-open the issue if you encounter a problem again!
