### ISSUE TITLE
Bug Report operation exceeded time limit 

### ISSUE THREAD

**Issue by tuan-dd** [mongodb-js/vscode#507]
Hi , so i want to combine two colletions to one collection ('Combine') so i run 
const database = 'convert';
const collection = 'Room';

// The current database to use.
use(database);

db.getCollection(collection).aggregate([{$lookup: {
    from: 'Price',
    localField: 'id',
    foreignField: 'id',
    as: 'result'
  }},{$unwind: '$result'
  },{$addFields: {
      price: '$result.onsiterate',
      priceDiscount:'$result.discount',
      discount:'$result.discount',
      rateType:'$result.ratetype',
      isRatePerStay:'$result.israteperstay',
      mealType:'$result.mealinclusiontype',
      taxType:'$result.taxtype',
  }},{$project: {
      id:1,
      hotelcode:1,
      roomamenities:1,
      roomtype:1,
      ratedescription:1,
      price:1,
      priceDiscount:1,
      discount:1,
      rateType:1,
      isRatePerStay:1,
      mealType:1,
      taxType:1,
  }},{$out: 'Combine'}]);

 error  'operation exceeded time limit ' ,  so i change timeout in vsc 
![image](https://user-images.githubusercontent.com/118432439/230000984-8e5e8f09-9819-4c18-b6ab-b51088859109.png)
but not working, help me

**Comment by Anemy** [comment]
Hi @tuan-dd I think you're looking at the wrong setting in VSCode. That setting is for `Diff editor`, not the MongoDB VSCode extension. In addition, at the moment the MongoDB VSCode extension doesn't have a setting around operation time limits.
Have you tried changing the `maxTimeMS` option in the aggregation options? https://www.mongodb.com/docs/manual/reference/method/db.collection.aggregate/
