### ISSUE TITLE
Mongo no longer appears as a language in the "Select a language" drop down.

### ISSUE THREAD

**Issue by abenham** [mongodb-js/vscode#511]
MongoDB has disappeared from the available languages when opening a new window.

1. Use ctrl-N to create a new window
2. Pick the "Select a language" option
3. No mongo db 

**MongoDB for VS Code v0.11.1
VS Code details...**

Version: 1.77.2 (user setup)
Commit: e344f1f539a80912a0e9357cec841f36ce97a4e2
Date: 2023-04-06T10:08:05.978Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.14393
Sandboxed: No

**Comment by alenakhineika** [comment]
Hey, correct. We've recently changed the extension so it no longer contributes a MongoDB language and uses the JavaScript language instead. We made this change to enable first-class support for JavaScript language features such as syntax highlighting, variable, function, and expression autocomplete, code refactoring, linting, and code formatting - those are capabilities that VSCode provides out of the box for JavaScript. The extension distinguishes playgrounds from other JavaScrit files by the file extension: `.mongodb.js` or `.mongodb`.
