### ISSUE TITLE
Shortcut to run the open playground

### ISSUE THREAD

**Issue by PauloHFS** [mongodb-js/vscode#518]
## Detailed Description

It's simple, a shortcut like ctrl + shift + R to run a active playground.

## Context

I don't want to use the mouse every time to run my queries.

**Comment by alenakhineika** [comment]
Hey, the extension already provides a shortcut to run a playground: `Option+Command+R` for MacOS and `Ctrl+Alt+R` for Windows and Linux. You can also reassign shortcuts according to your preferences. Open `Settings... -> Keyboars Shortcuts`, search for the command you want to assign a shortcut to, and pick your shortcut for it. All the commands for all the extensions are available on that list.
