### ISSUE TITLE
Connectivity issues

### ISSUE THREAD

**Issue by ezeobac3** [mongodb-js/vscode#519]
#### Summary

it's very difficult securing a connection with connection string in VS Code environment. Error in connection report always gets returned. Downloaded the extension, downloaded and installed the mongoDB and mongo shell packages. Any help with this would be nice please. Thanks!

#### Environment

- node.js / npm versions:
- OS:

**Comment by Anemy** [comment]
Hi @ezeobac3 - is this an error for VSCode specifically or for MongoDB connectivity? Can you connect with other tools like the MongoDB shell, mongosh? https://www.mongodb.com/try/download/shell
To help us understand the issue:
- Can you give us some information about the connection? Is it to a local instance, or to somewhere remote like Atlas?
- Are you using authentication? What method?
- What is the error that is returned?

**Comment by Anemy** [comment]
Feel free to reopen if there's more information.
