### ISSUE TITLE
Performance Woes. Creating a New Playground in VS Code Triggers Slowdowns and Overloads CPU Usage

### ISSUE THREAD

**Issue by frnnnnn** [mongodb-js/vscode#520]
**Resume**
When I want to create a new playground from the bottom left, from the +. the vs code slows down and the mouse pointer appears with a constant intermittent loading circle and the cpu is overloaded up to about 80-90% and the application becomes almost unusable.

**error report
Comportamiento actual
code/Gist
code/expected behavior**
That vscode does not slow down and works optimally.

**environment**
-Mongodb in vscode
-Windows 11
**possible solution**
That vscode does not slow down and works optimally.

**Comment by alenakhineika** [comment]
Hey, could you please tell us which version of VSCode and the extension you use? Do you experience the same issue when you create a playground from the command palette?

**Comment by frnnnnn** [comment]
the version I'm using is the latest (1.78.1). and yes, the same thing happens when I create it from the command palette

**Comment by frnnnnn** [comment]
already solved

**Comment by Anemy** [comment]
@frnnnnn Can we close this ticket then? Let us know if you find a way to reproduce this.
