### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Ankan-cyber** [mongodb-js/vscode#525]
- Issue Type: `Performance`
- Extension Name: `mongodb-vscode`
- Extension Version: `1.0.1`
- OS Version: `Linux arm64 6.1.21-v8 `
- VS Code version: `1.78.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/mongodb.mongodb-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Anemy** [comment]
@Ankan-cyber what were you doing when you experienced the high CPU load?

**Comment by Ankan-cyber** [comment]
just adding a new mongodb connection

**Comment by Anemy** [comment]
@Ankan-cyber if you have a moment can you attach the cpu file in the issue description?
A few more questions to help us debug:
Was there a noticeable slowdown of VSCode or the extension that lead you to creating this?
Do you remember if you were adding a connection using the webview, or with the connection string input? I'm thinking a webview could have caused some cpu load as it is essentially running a browser. 
If it wasn't that it could be that loading the extension could be optimized more, we do bundle things together and webpack but don't do too many performance optimization like minifying there.

**Comment by Ankan-cyber** [comment]
No I currently don't have the cpu file but I am adding connection through connection string and the vs code running fine there was an notification in vscode telling that mongodb extension task taking too long to respond and stopping other extensions some message like that when i opened the show running extension in vs code the mongodb extension is unresponsive and taking a lot of time to respond

**Comment by Anemy** [comment]
@Ankan-cyber 
I created a ticket on jira to investigate what we can do to improve the code load and startup performance of the extension. 
Going to close this ticket if that's alright, you can add yourself as a watcher on jira to get notifications.
https://jira.mongodb.org/browse/VSCODE-420 

Thanks for reporting the issue and the quick followups!
