### ISSUE TITLE
Update on documents

### ISSUE THREAD

**Issue by jeanbrazcosta** [mongodb-js/vscode#558]
Type: <b>Feature Request</b>

Why is there no option to press shift + f10 on a document and do an update, you only have the option to insert a new document, delete or search?

Extension version: 1.0.2
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by alenakhineika** [comment]
Hey, you may edit a single document [opened from a collection tree view](https://www.mongodb.com/docs/mongodb-vscode/databases-collections/#documents) or [shown in the playground results pane](https://www.mongodb.com/docs/mongodb-vscode/read-document-playground/#read-one-document). Use `Ctrl + S` (Windows/Linux) or `Cmd + S` to save the edited document to the MongoDB database. Hope this is helpful! Feel free to reach out if you have any questions.
