### ISSUE TITLE
Feature Request: Allow to spin up new container and automatically add it to connections and connect to it

### ISSUE THREAD

**Issue by CodingSpiderFox** [mongodb-js/vscode#570]
## Feature Request

When a docker installation is detected on the system, allow to directly spin up a new mongoDB in docker and connect to it.

## Detailed Description

When that option is chosen automatically create a new container with the mongodb:latest docker image, a fixed username (e.g. "dev") and a random 16 chars password
When the port 27017 is already in use, ask the user which port the container should bind.
Then add the connection to the connections list, connect immediately and open the connection's tree item first hierarchy so I can start adding a database on the server

## Context

I want to be able to set up a DB for testing quickly

**Comment by Anemy** [comment]
Cool idea! If possible please add it this to our feedback forum which we use for managing feature requests (it has tracking and upvoting): https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code

**Comment by CodingSpiderFox** [comment]
https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/47180441-when-a-docker-installation-is-detected-on-the-syst
