### ISSUE TITLE
Questionpymongo.errors.AutoReconnect

### ISSUE THREAD

**Issue by Milind-Shende** [mongodb-js/vscode#571]
## I have been dumping my data to mongodb and i am getting pymongo.errors.AutoReconnect Please can anyone tell me what the problem.?

![image](https://github.com/mongodb-js/vscode/assets/103568452/150a23ba-a052-4b57-971d-f52d20915691)
![image](https://github.com/mongodb-js/vscode/assets/103568452/474547a4-8040-4384-8546-60ac08096ecb)
![image](https://github.com/mongodb-js/vscode/assets/103568452/a5f7deda-3a2b-4aea-89db-732655f1deb3)

**Comment by alenakhineika** [comment]
Hey, you have opened the issue in the repository of the MongoDB extension for VSCode. Based on your screenshot you are using the pymongo driver in your IDE which is not relevant to the current extension. Try to ask your question on the [MongoDB Community Forum](https://www.mongodb.com/community/forums/).

**Comment by Milind-Shende** [comment]
But in last project I used same code to dump my data to MongoDB and it works for me but now it show's error of AutoReconnect. ok Thanks I will ask to MongoDB
