### ISSUE TITLE
Unable to save document

### ISSUE THREAD

**Issue by erikvallet** [mongodb-js/vscode#576]
Hi,
I can't save a document after edit, in VSCode with your extension : 
"Unable to save document: command findAndModify is unsupported, correlationID = 1779bcd65584350ee5635308"

My version of MongoDB is upper than the 4.0, so why the extension use findAndModify ?

Thanks to all.

**Comment by alenakhineika** [comment]
Hey, could you please share with us which exact version of the MongoDB server you are running? Is it localhost or maybe Atlas? And which version of the extension it is?

**Comment by Rikbagg** [comment]
Version of extension : 1.1.0
Mongo version : 6.0.8
In a Atlas server

**Comment by Rikbagg** [comment]
Yes, in Composs, no problem.

I list my recordings, then click on Edit document : I modify it and type a Ctrl+S.

![image](https://github.com/mongodb-js/vscode/assets/38683750/5d112b8b-9a4d-406d-bc5b-fa95f99128d5)
![image](https://github.com/mongodb-js/vscode/assets/38683750/f1b9d2c2-dab3-42e0-b34c-2fa54688ac1b)

**Comment by alenakhineika** [comment]
Thank you for sharing screenshots! The team will further investigate this unexpected behavior. You can use this [ticket](https://jira.mongodb.org/browse/VSCODE-459) to track the progress.

**Comment by Rikbagg** [comment]
Thank you, good job !

**Comment by alenakhineika** [comment]
Hey, looks like you are connecting to Atlas Data Federation, which is read-only, therefore when you try to edit a document, you get the error. We will update the error message to make it more informative and helpful in cases like this. Thx for reporting the issue!
