### ISSUE TITLE
Bug Report - MongoDB for VS Code keeps opening playground tab, unsolicited

### ISSUE THREAD

**Issue by geoshak** [mongodb-js/vscode#582]
## Bug Report
MongoDB for VS Code keeps opening playground tab, unsolicited.
I close it, it opens up again, repeatedly.

#### Expected Behavior/Code
The playground tab should only open when solicited by the user

#### Environment
Linux Mint 22

**Comment by alenakhineika** [comment]
Hey, this is for sure an unexpected behavior of the extension! What version of VSCode and the extension are you using? Would it be possible to share a screen recording, so we could see how this looks? (pls ensure that no sensitive data will appear on the recording)

**Comment by geoshak** [comment]
I was using latest versions of both on the time of the initial post. However, the issue seems to have gone away. Thanks for the reply anyways! Will close this.
