### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mwihoti** [mongodb-js/vscode#584]
- Issue Type: `Performance`
- Extension Name: `mongodb-vscode`
- Extension Version: `1.2.0`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.81.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Dan/AppData/Local/Temp/mongodb.mongodb-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by alenakhineika** [comment]
Hey, could you please answer on couple of questions to help us further investigate this issue:

- What were you doing when you experienced the high CPU load?
- If you have a moment can you attach the cpu file in the issue description?
- Was it a noticeable slowdown of VSCode or the extension that led you to create this issue?
- Were you adding a connection using the connection form, or with the connection string input?

Thank you in advance!

**Comment by alenakhineika** [comment]
Closing the issue because of lack of activity. Feel free to reopen if you have more details to share.
