### ISSUE TITLE
Feature Request - Query Performance

### ISSUE THREAD

**Issue by tehjinxi** [mongodb-js/vscode#646]
## Feature Request
- Now the vscode extension does not provide any query performance, exp how many MS that query use to run

## Possible Implementation

- Return the result of how long does query take to get result

**Comment by alenakhineika** [comment]
Hey, thank you for reaching out! You actually can use MongoDB playground and run the [explain](https://www.mongodb.com/docs/manual/reference/method/cursor.explain/) command to get detailed information about query execution. Is it something you were looking for?

**Comment by alenakhineika** [comment]
Сlosing because of a lack of activity.
