### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Liameternal** [mongodb-js/vscode#697]
## Question
run all or selection from playgroud button  missing

![image](https://github.com/mongodb-js/vscode/assets/25942745/60f7446f-eeec-48b6-9668-ce38fa7e06f7)

## Additional context
there is supposed to have a shortcut button which trigger run all or selection from playgroud action, I inaccidently click hide this button, then it disppear. Looking through vsc settings, can't find how to reset this button. Is there anyone knowing how to reset this button?

**Comment by Anemy** [comment]
Hi @Liameternal - if you right click the split view it should show an option to un-hide the action:
![Screenshot 2024-03-04 at 1 07 17 PM](https://github.com/mongodb-js/vscode/assets/1791149/0892aa20-a35a-4acb-9d80-0c5bf97482f5)
Clicking on that option brought it back for me. 
Thanks for using the extension! Let us know if you have any feedback or ideas for how we can improve it. We have a feedback forum here: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code

**Comment by Liameternal** [comment]
@Anemy I clicked this option, the button came back. Thank you!
![image](https://github.com/mongodb-js/vscode/assets/25942745/1a2efd4e-3be5-424f-83b5-e964e77dfd3b)
![image](https://github.com/mongodb-js/vscode/assets/25942745/a6c77ece-4483-4e46-8c19-d65d5d18ee69)
