### ISSUE TITLE
Shows distracting and irrelevant "Currently connected to..." line and button at the top of all .js files

### ISSUE THREAD

**Issue by dancherb** [mongodb-js/vscode#740]
A line "Currently connected to..." (with a button) shows at the top of all .js files when the extension is active, even when irrelevant - i.e. editing a normal .js file which has nothing to do with the database. Extension functionality should be limited to the sidebar and files directly interacting with the database - it should not add irrelevant and distracting buttons to other files.

![mongodb](https://github.com/mongodb-js/vscode/assets/32280121/3077ecd0-7391-41e6-b7c4-911a9f074110)

**Comment by Anemy** [comment]
Thanks for opening, this is a bug, created a ticket to track a fix: https://jira.mongodb.org/browse/VSCODE-538

**Comment by alenakhineika** [comment]
The fix was shipped with the 1.8.0 release of the extension. Thank you for reporting the issue!
