### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MilanNemeth-Eviden** [mongodb-js/vscode#762]
I want to save my connection into the workspace settings.

I can't find the **Hide Option To Choose Where To Save New Connections** setting nor the option itself anywhere, so the **Default Connection Saving Location** also doesn't take effect. How can I achieve saving the connection in the workspace?

 I'd just like to be able to save my connection as a setting, so my coworkers won't have to set it up manually. How can I achieve this?

**Comment by alenakhineika** [comment]
Hey, the extension settings can be opened via `Code -> Settings...` in the Menu, then search my `mongodb`. There will be the `Mdb › Connection Saving: Default Connection Saving Location` dropdown or the `mdb.connectionSaving.defaultConnectionSavingLocation` json setting to set your default saving location. I just tried with the extension v1.6.1 and when I entered a new connection via the command palette or connection form it didn't ask to specify a location for each new connection, but used a default setting instead. Could you check if this workflow works for you and that you are on the latest version of the extension? If you still have the issue, could you provide more detailed steps to reproduce? Thx in advance!

**Comment by MilanNemeth-Eviden** [comment]
@alenakhineika you're right. For some reason, I've expected that the connection will be stored in the workspace's settings.json, so I could be able to commit it in source control, or set it up in a devcontainer.json, but that's not the case, and now, after reading the docs back and forth many times, I'm pretty sure that there's no solution to my original issue, which was sharing my connection settings with others without the need of any kind of further manual intervention.

**Comment by alenakhineika** [comment]
We have actually received a similar feature request before https://github.com/mongodb-js/vscode/issues/368. Please share this idea on our [feedback forum](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code). If it garners enough votes, we can prioritize it in our development schedule.
