### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by yashrbankar** [mongodb-js/vscode#800]
I am facing issue in running mongodb for vscode for wsl (ubantu)

GETTING ERROR BYVSCODE :
Error running command mdb.addConnection: command 'mdb.addConnection' not found. This is likely caused by the extension that contributes mdb.addConnection.

**Comment by eag-fbio** [comment]
Also got same error

**Comment by alenakhineika** [comment]
Hey, sorry that the new version of the extension fails to activate and causes trouble! We will release the fix on Monday. I will message here when it is out, so you can upgrade.

**Comment by alenakhineika** [comment]
Hey, the 1.8.1 release is out! Please try it out and let us know if this resolves the issue.

**Comment by timohuovinen** [comment]
Me too

**Comment by timohuovinen** [comment]
@alenakhineika yes, updating has fixed the issue for me

**Comment by alenakhineika** [comment]
Thank you for verifying!

**Comment by eag-fbio** [comment]
Seems to work for me too.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alenakhineika** [comment]
Please upgrade the extension to the 1.8.1 version. This should contain the fix for the problem.

**Comment by eag-fbio** [comment]
Done, and verified.
