### ISSUE TITLE
Error connecting to Mongodb localhost:27017  instance in GitHub Codespace. 

### ISSUE THREAD

**Issue by my382** [mongodb-js/vscode#833]
#### Current Behavior

Open GitHub codespace from repository.  Add mongodb extension in Codespace environment and try to add connection. 
Mongodb instance doesn't get created. It fails to connect to localhost:27017 and throws an error every time

Unable to connect: connect ECONNREFUSED 127.0.0.1:27017, connect ECONNREFUSED ::1:27017

#### Expected Behavior/Code

Expected outcome is localhost:27017 should be connected successfully from Mongodb extension. 

#### Environment

node.js v20.17.0
npm v10.8.2
mongodb extension installed on GitHub Codespace

## Error image
![image](https://github.com/user-attachments/assets/5eee5dd7-c0ff-4cb6-ba85-ef14f71a4b92)

**Comment by Anemy** [comment]
@my382 From my understanding a GitHub codespace is running on GitHub's servers. Is the MongoDB instance you're trying to connect to also in the codespace? Or is it on your machine?

**Comment by my382** [comment]
@Anemy, Thank you for looking into it.  I did install MongoDB extension in Github codespace. I tried connecting by accessing its interface but no luck.  Mongodb refuses the connection. What I notice further, if I have mongo docker image, created a container and started then I'm able to connect mongodb by executing command on Github codespace terminal as 
docker exec [container id] bash
root@[some id]: mongosh

It connects to mongodb://127.0.0.1:27017

I do not have access to mongod in Codespace.  Please let me know if any alternatives I should try.

**Comment by my382** [comment]
@nirichev, Thank you for your reply.  I am working on Github Codespace only and not on my local machine. I installed MongoDB extension in Github Codespace. Usually, it comes with an interface to connect to MongoDB either through localhost or by providing necessary connection string. I tried both the approaches, but it didn't help. 

Secondly, for my Node & mongo application, I took mongo docker image, created container and made it up & run. Docker container for mongo runs successfully without an issue but if I try to access connection through mongodb://mongo:27017/test it does not work. 

What I notice further, if I have mongo docker image, created a container from it and started then I'm able to connect to MongoDB by executing command on Github Codespace terminal as
docker exec [container id] bash
root@[some id]: mongosh

It connects to mongodb://127.0.0.1:27017/test and gives me prompt as 'test>' to execute further commands. 

This approach is through terminal and not programmatically. 

I am looking for 
1. How to connect to a MongoDB instance from Github Codespace 
2. Once step 1 is successful then, after running docker containers for Node and mongo, a connection should be established. 

Please let me know if you need more details.

**Comment by my382** [comment]
@nirichev and @Anemy , In Github Codespace,  after running Mongo docker container, MongoDB extension UI connected to localhost:27017. Also, through my application after running NodeJS server, it was able to connect to DB programmatically. 

The understanding is it requires mongo docker container or dev container up & running in Codespace.
