### ISSUE TITLE
querysrv

### ISSUE THREAD

**Issue by sampreethi303** [mongodb-js/vscode#876]
![Screenshot (43)](https://github.com/user-attachments/assets/12bf0e4c-2dc0-4679-a7b5-59cc1d33c7c9)
Type: <b>Bug</b>

cant connect to my mongodb atlas to my vscode

Extension version: 1.9.3
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.79GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/reddy/student-app --crash-reporter-id 3fa21156-8ed3-41b9-8a55-13fbde8f4c5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by Anemy** [comment]
@sampreethi303 It looks like that URL in the screenshot isn't formed right. The cluster link should be different.
In the Atlas UI when you are connecting can you try using this to help get the right URL format. On the project `Clusters` page:
<img width="295" alt="Screenshot 2024-11-19 at 11 08 01 AM" src="https://github.com/user-attachments/assets/e8d17b8e-bb92-4e76-98d1-343cc76be86d">


**Also - if those are your real database credentials in that screenshot you should cycle/re-create them.**

I'm going to close this as this is a connectivity issue and not related to the VSCode extension. Thanks for checking out the extension!
