### ISSUE TITLE
Issue Attaching Identity File in MongoDB with SSH Proxy

### ISSUE THREAD

**Issue by alvaroico** [mongodb-js/vscode#901]
#### Current Behavior

When I try to configure an advanced connection in MongoDB using SSH Proxy, I cannot attach an identity file in the SSH with Identity File section. I click the icon and then the file, but it is not loaded.

#### Expected Behavior/Code

I expected the identity file to be successfully attached when selected.

#### Environment

- node.js / npm versions: node v22.12.0 / npm 10.9.0
- OS: Linux Bilu 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- VSCode: Version 1.95.3
  - Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
  - Date: 2024-11-13T14:50:04.152Z
  - Electron: 32.2.1
  - ElectronBuildId: 10427718
  - Chromium: 128.0.6613.186
  - Node.js: 20.18.0
  - V8: 12.8.374.38-electron.0
  - OS: Linux x64 6.8.0-49-generic

#### Possible Solution

N/A

#### Additional Context/Screenshots
- Select a file 
![image](https://github.com/user-attachments/assets/0598ec01-d67d-40d7-adee-addd73872faa)

**Comment by alenakhineika** [comment]
Hey, thank you for reaching out and reporting the bug! This is a known issue. You can track the progress here https://jira.mongodb.org/browse/VSCODE-658. We are going to ship the fix sith the next release. I will post an update here when the release is out.

**Comment by alenakhineika** [comment]
Hey, we have released the 1.11.0 version that includes the fix for selecting files on the form. Hopefully, now you will be able to connect! Sorry for the inconvenience and please let us know if you encounter any issues.
