### ISSUE TITLE
can not run playground when there is a `babel.config.js` in project root?

### ISSUE THREAD

**Issue by hushicai** [mongodb-js/vscode#91]
/Users/hushicai/data/work/myproject/babel.config.js: Error while loading config - Cannot find module '/Users/hushicai/data/work/myproject/babel.config.js'

![image](https://user-images.githubusercontent.com/1249423/82000004-92744200-9689-11ea-961b-97bed36628e6.png)

**Comment by hushicai** [comment]
It's fine, when there is no `babel.config.js` in project root。

**Comment by Anemy** [comment]
The fix will be in the next release - early next week. Thanks for bringing it up!

**Comment by Anemy** [comment]
@hushicai The fix is now live in version 0.0.3 - if you update and the issue still exists please reopen. Thanks again for letting us know.
