### ISSUE TITLE
UUID fields are shown as Base64

### ISSUE THREAD

**Issue by frankie567** [mongodb-js/vscode#93]
Hi there!

First, thank you for this extension, it looks very promising :)

I have a collection with documents containing [`UUID` fields](https://docs.mongodb.com/manual/reference/method/UUID/) (standard, not legacy). When I browse those documents in the extension, they are shown like this:

```json
{
  "_id": "5e58eae46015f74c61dd6af0",
  "my_uuid": "Z9vkmswWSKy2mIkKXpCbMg=="
}
```

I would have expected them to be shown as:

```json
{
  "_id": "5e58eae46015f74c61dd6af0",
  "my_uuid": UUID("67dbe49a-cc16-48ac-b698-890a5e909b32")
}
```

Robot 3T (for example) does this well. This is a quite small QOL improvement, but I think it was worth reporting it.

Cheers!

**Comment by milkshakeuk** [comment]
we use dotnet guids so can we support hat also thanks.

**Comment by Anemy** [comment]
Sweet - we've been chatting on how people would like to see bson files represented. We'll be visiting it in upcoming work - probably by providing a setting for how the user wants them displayed and defaulting to the most desired way. Thanks for bring it up. I'll post here once we've got it in progress.

**Comment by donavon** [comment]
I just created  [JIRA ticket VSCODE-118](https://jira.mongodb.org/projects/VSCODE/issues/VSCODE-118) on a related issue. I'm using UUIDs as my `_id` field and the extension not only can't display them properly in the list (I'm seeing base64 ended as well), but even worse is the that when I click on one, I get a "Unable to find document" toast message.

<img width="467" alt="Screen Shot 2020-05-16 at 12 08 07 AM" src="https://user-images.githubusercontent.com/887639/82110419-736ac400-970c-11ea-9c38-5efbbd6540d7.png">

<img width="326" alt="Screen Shot 2020-05-16 at 12 10 40 AM" src="https://user-images.githubusercontent.com/887639/82110435-91382900-970c-11ea-8fd5-594002e5d710.png">

**Comment by mmarcon** [comment]
Closing this here and tracking it in JIRA.

**Comment by PauloDanielCarneiro** [comment]
Any news about this?

**Comment by frankie567** [comment]
Looks like [JIRA ticket VSCODE-118](https://jira.mongodb.org/projects/VSCODE/issues/VSCODE-118) was closed, but it didn't solve the issue for UUID that are fields of the document.

I think the current ticket should be reopened.

**Comment by mmarcon** [comment]
I think there were 2 issues being discussed here:

1. how documents are displayed in the Collection View (when in the tree view you right-click on `Documents` and select `View Documents`).
2. the problem of opening documents by clicking on their `_id` in the tree view.

2 is what we fixed in [VSCODE-118](https://jira.mongodb.org/projects/VSCODE/issues/VSCODE-118).
1 we have not addressed and I'd consider it a feature request. The reason why I would be reluctant to just do it is that the resulting editor then would not be just a simple JSON editor, we'd have to also add probably a new language mode that understands things like `UUID("a91ee20e-4a11-463c-9493-740725f4edc2")`, and then adjust the document editing experience to work with that new language mode. Could you create this as a feature request in our [feedback portal](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code)? Having it there makes it easier for us to triage and aggregate it to the feedback of our customers.

**Comment by PauloDanielCarneiro** [comment]
I don't know how the connection is made

> I think there were 2 issues being discussed here:
> 
> 1. how documents are displayed in the Collection View (when in the tree view you right-click on `Documents` and select `View Documents`).
> 2. the problem of opening documents by clicking on their `_id` in the tree view.
> 
> 2 is what we fixed in [VSCODE-118](https://jira.mongodb.org/projects/VSCODE/issues/VSCODE-118).
> 1 we have not addressed and I'd consider it a feature request. The reason why I would be reluctant to just do it is that the resulting editor then would not be just a simple JSON editor, we'd have to also add probably a new language mode that understands things like `UUID("a91ee20e-4a11-463c-9493-740725f4edc2")`, and then adjust the document editing experience to work with that new language mode. Could you create this as a feature request in our [feedback portal](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code)? Having it there makes it easier for us to triage and aggregate it to the feedback of our customers.

About 2:
How can I see an uuid when I open a document?  When I click in one it appears as a binary

**Comment by mmarcon** [comment]
@PauloDanielCarneiro good point. At the moment, we don't have a built-in way to display UUIDs (or any other binary type) in a more readable way. The editor will always display documents in EJSON.

As a temporary workaround, while there is no built-in solution, if your use case is to only see the documents in the collection in a more readable way, you can use a playground and do this:

```javascript
const { inspect } = require('util');
use('your_db');
db.your_collection
  .find({/*optionally add a query here*/})
  .toArray()
  .map(doc => {
    doc._id = inspect(doc._id).replaceAll('\"', '');
    return doc;
  });
```

**Comment by mmarcon** [comment]
Yes, `util` is Node's `util`. 

You could try this variation:

```javascript

**Comment by megasuperlexa** [comment]
4 years later, and the correct JIRA I think is this https://jira.mongodb.org/browse/VSCODE-470
(still open)
